// Seed: non-US AI lawsuits / regulatory enforcement actions.
//
// Each entry has been verified via web search (April 2026) against at least one
// credible source (court judgment, regulator press release, or major outlet).
// Fields left NULL where the public record is unclear — this script does NOT
// invent dates, judges, or outcomes. Safe to re-run: ON CONFLICT DO NOTHING.
//
// Run: node server/db/scripts/seed_global_lawsuits.js

import pool from '../pool.js';

const CASES = [
  // ── UK ──────────────────────────────────────────────────────────────────────
  {
    case_name: 'Getty Images v. Stability AI (UK)',
    plaintiffs: ['Getty Images (US) Inc.', 'Getty Images International'],
    defendants: ['Stability AI Limited'],
    court: 'High Court of Justice of England and Wales (Chancery Division)',
    judge: 'Mrs Justice Joanna Smith',
    jurisdiction: 'UK',
    district: 'England & Wales',
    circuit: null,
    status: 'decided',
    case_type: 'copyright',
    key_issues: [
      'copyright in AI training data',
      'secondary copyright infringement under ss.22/23 CDPA',
      'AI model weights as "copy"',
      'trademark infringement by Stable Diffusion outputs',
      'extraterritorial scope of UK copyright',
    ],
    filing_date: '2023-01-16',
    last_update: '2025-11-04',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: 'Court largely rejected Getty\'s copyright claims (Getty abandoned primary training-data infringement and database right claims before closing). Held AI model weights are not a "copy" of training images. Found "extremely limited" trademark infringement under s.10(1)/10(2) Trade Marks Act for early Stable Diffusion versions; dismissed s.10(3) claim. First UK judgment on genAI copyright.',
    settlement_amount: null,
    case_url: 'https://www.judiciary.uk/wp-content/uploads/2025/11/Getty-Images-v-Stability-AI.pdf',
    source_url: 'https://www.twobirds.com/en/insights/2025/uk/stability-ai-defeats-getty-images-copyright-claims-in-first-of-its-kind-dispute-before-the-high-cour',
    summary: 'Getty Images sued Stability AI in the English High Court alleging copyright, database right and trademark infringement from the use of Getty\'s watermarked images to train Stable Diffusion. In November 2025 Mrs Justice Smith handed down the first UK genAI judgment: Getty had abandoned its primary copyright claims at trial because training occurred outside the UK, the court held AI model weights do not "copy" training images, and only very narrow trademark infringement was found on early Stable Diffusion outputs.',
    curriculum_relevance: 'Landmark UK genAI ruling — establishes that UK copyright is territorially limited when training happens abroad, and that model weights are not stored copies. Essential for any media organisation considering UK litigation strategy or training-data licensing.',
    citation: '[2025] EWHC 2863 (Ch)',
  },

  // ── India ───────────────────────────────────────────────────────────────────
  {
    case_name: 'ANI Media Pvt. Ltd. v. OpenAI',
    plaintiffs: ['Asian News International (ANI)'],
    defendants: ['OpenAI Inc.', 'OpenAI OpCo LLC'],
    court: 'Delhi High Court',
    judge: null,
    jurisdiction: 'India',
    district: 'Delhi High Court',
    circuit: null,
    status: 'active',
    case_type: 'copyright',
    key_issues: [
      'use of Indian news content to train ChatGPT',
      'section 52 Copyright Act fair use',
      'jurisdiction over foreign AI provider',
      'false attribution / hallucinations',
      'rights of Indian news publishers',
    ],
    filing_date: '2024-11-19',
    last_update: '2025-08-18',
    next_deadline: null,
    next_deadline_notes: 'Judgment reserved after hearings',
    outcome: null,
    settlement_amount: null,
    case_url: null,
    source_url: 'https://theleaflet.in/digital-rights/ani-v-openai-in-the-delhi-hc-everything-so-far-and-all-that-is-at-stake',
    summary: 'Indian news agency ANI sued OpenAI in the Delhi High Court alleging that ChatGPT was trained on ANI\'s copyrighted news content without authorisation and produces false attributions. The Digital News Publishers Association joined as intervener. The court appointed two Amici Curiae and framed four questions: whether storing copyrighted data for training is infringement, whether generating responses using it is infringement, whether s.52 fair use applies, and whether Indian courts have jurisdiction over OpenAI given its servers are abroad. Judgment is reserved.',
    curriculum_relevance: 'The landmark Indian AI copyright case — first test of fair use under s.52 of the Indian Copyright Act for AI training, and of Indian jurisdiction over a foreign AI provider. Central to the position of Indian news publishers.',
    citation: null,
  },

  // ── Italy ───────────────────────────────────────────────────────────────────
  {
    case_name: 'Garante v. OpenAI (ChatGPT — Italy)',
    plaintiffs: ['Garante per la protezione dei dati personali (Italian DPA)'],
    defendants: ['OpenAI, L.L.C.'],
    court: 'Garante per la protezione dei dati personali',
    judge: null,
    jurisdiction: 'Italy',
    district: 'Italian DPA',
    circuit: null,
    status: 'appealing',
    case_type: 'privacy',
    key_issues: [
      'GDPR Article 5 / 6 lawful basis for AI training',
      'GDPR Article 33 breach notification',
      'transparency to users (Arts. 12, 13)',
      'age verification for minors',
      'March 2023 data breach',
    ],
    filing_date: '2023-03-31',
    last_update: '2024-12-20',
    next_deadline: null,
    next_deadline_notes: 'OpenAI has stated it will appeal the Garante\'s decision',
    outcome: 'On 20 December 2024 the Garante found OpenAI in breach of GDPR Arts. 5(1)(a), 5(2), 6, 12, 13, 24, 25, 33 and 83(5)(e); imposed a €15 million administrative fine and ordered a 6-month public awareness campaign. First major EU GDPR enforcement decision against a genAI provider.',
    settlement_amount: '€15,000,000',
    case_url: null,
    source_url: 'https://www.lewissilkin.com/en/insights/2025/01/14/openai-faces-15-million-fine-as-the-italian-garante-strikes-again-102jtqc',
    summary: 'The Italian Garante briefly banned ChatGPT in March 2023 over the March 2023 data breach and lack of GDPR compliance. Following a formal procedure, on 20 December 2024 the Garante issued a €15 million fine against OpenAI for multiple GDPR violations including lack of lawful basis for training, failure to notify the breach, and lack of age verification. OpenAI has said it will appeal.',
    curriculum_relevance: 'The first meaningful GDPR enforcement decision against a generative AI provider. Establishes the EU regulatory template — lawful basis, transparency, breach notification, minors — that every AI company operating in Europe must now answer to.',
    citation: null,
  },

  // ── France ──────────────────────────────────────────────────────────────────
  {
    case_name: 'CNIL investigation into OpenAI (France)',
    plaintiffs: ['Commission nationale de l\'informatique et des libertés (CNIL)'],
    defendants: ['OpenAI, L.L.C.'],
    court: 'Commission nationale de l\'informatique et des libertés',
    judge: null,
    jurisdiction: 'France',
    district: 'French DPA',
    circuit: null,
    status: 'active',
    case_type: 'privacy',
    key_issues: [
      'lawful basis for AI training',
      'transparency',
      'accuracy of AI-generated personal data',
      'data subject rights',
    ],
    filing_date: '2023-04-11',
    last_update: null,
    next_deadline: null,
    next_deadline_notes: 'Investigation ongoing; no final enforcement decision as of April 2026',
    outcome: null,
    settlement_amount: null,
    case_url: null,
    source_url: 'https://www.cnil.fr/en/artificial-intelligence-action-plan-cnil',
    summary: 'The CNIL received at least five complaints against OpenAI in spring 2023 (including from MP Éric Bothorel and lawyer Zoé Villain) and opened a control procedure examining ChatGPT\'s lawfulness, transparency and accuracy. As of April 2026 the investigation remains open with no final decision published.',
    curriculum_relevance: 'France\'s pending investigation is one of the handful of serious EU DPA inquiries still active. Useful context for understanding how fragmented EU enforcement against OpenAI has been compared to the Italian Garante\'s more decisive action.',
    citation: null,
  },

  // ── Canada ──────────────────────────────────────────────────────────────────
  {
    case_name: 'OPC v. OpenAI (Canada — ChatGPT joint investigation)',
    plaintiffs: ['Office of the Privacy Commissioner of Canada (OPC)', 'Commission d\'accès à l\'information du Québec', 'Office of the Information and Privacy Commissioner of British Columbia', 'Office of the Information and Privacy Commissioner of Alberta'],
    defendants: ['OpenAI, L.L.C.'],
    court: 'Office of the Privacy Commissioner of Canada',
    judge: null,
    jurisdiction: 'Canada',
    district: 'Federal / Quebec / BC / Alberta joint investigation',
    circuit: null,
    status: 'decided',
    case_type: 'privacy',
    key_issues: [
      'PIPEDA consent for personal data used in training',
      'accuracy of personal data produced by AI',
      'transparency about training data',
      'openness / accountability',
    ],
    filing_date: '2023-04-04',
    last_update: '2025-06-30',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: 'In June 2025 the OPC concluded the joint federal–provincial investigation, finding OpenAI had violated PIPEDA by collecting personal information from Canadians without proper consent, failing to ensure the accuracy of personal data generated by ChatGPT, and lacking sufficient transparency about training data. OpenAI accepted a number of concessions as part of the resolution.',
    settlement_amount: null,
    case_url: null,
    source_url: 'https://www.priv.gc.ca/en/opc-news/news-and-announcements/2023/an_230525-2/',
    summary: 'The Office of the Privacy Commissioner of Canada launched a joint investigation with the Quebec, BC and Alberta privacy authorities in April 2023 after a complaint about OpenAI collecting Canadians\' personal information without consent. In June 2025 the OPC announced formal findings that OpenAI had breached PIPEDA on consent, accuracy and transparency — one of the most concrete regulatory findings against OpenAI by any Western government.',
    curriculum_relevance: 'Canada produced one of the earliest substantive regulatory findings against OpenAI anywhere in the world. Useful as a comparison point to the EU Garante decision and to illustrate how multi-regulator joint investigations work.',
    citation: null,
  },

  // ── Poland ──────────────────────────────────────────────────────────────────
  {
    case_name: 'UODO v. OpenAI (ChatGPT — Poland)',
    plaintiffs: ['Polish Office for Personal Data Protection (UODO)', 'Łukasz Olejnik (complainant)'],
    defendants: ['OpenAI, L.L.C.'],
    court: 'Urząd Ochrony Danych Osobowych (UODO)',
    judge: null,
    jurisdiction: 'Poland',
    district: 'Polish DPA',
    circuit: null,
    status: 'active',
    case_type: 'privacy',
    key_issues: [
      'lawful basis for processing',
      'accuracy / right to rectification',
      'transparency',
      'data subject access requests',
    ],
    filing_date: '2023-09-20',
    last_update: null,
    next_deadline: null,
    next_deadline_notes: 'Investigation ongoing',
    outcome: null,
    settlement_amount: null,
    case_url: null,
    source_url: 'https://techcrunch.com/2023/09/21/poland-chatgpt-gdpr-complaint-probe/',
    summary: 'On 20 September 2023 the Polish UODO opened an investigation into OpenAI following a GDPR complaint from privacy researcher Łukasz Olejnik. The complaint concerns OpenAI\'s handling of his request to rectify inaccurate information in a ChatGPT-generated biography, and its responses to subject access requests — alleging unlawful, unreliable and opaque processing.',
    curriculum_relevance: 'Raises the practical question of how GDPR rectification and subject-access rights work when the "data" is generated stochastically by an LLM. Important example for curriculum discussion of AI hallucinations and data subject rights.',
    citation: null,
  },

  // ── Spain ───────────────────────────────────────────────────────────────────
  {
    case_name: 'AEPD investigation into OpenAI (Spain)',
    plaintiffs: ['Agencia Española de Protección de Datos (AEPD)'],
    defendants: ['OpenAI, L.L.C.'],
    court: 'Agencia Española de Protección de Datos',
    judge: null,
    jurisdiction: 'Spain',
    district: 'Spanish DPA',
    circuit: null,
    status: 'active',
    case_type: 'privacy',
    key_issues: [
      'lawful basis for training',
      'transparency',
      'GDPR compliance at EU level',
    ],
    filing_date: '2023-04-13',
    last_update: null,
    next_deadline: null,
    next_deadline_notes: 'Investigation ongoing; referred to EDPB for coordinated EU response',
    outcome: null,
    settlement_amount: null,
    case_url: null,
    source_url: 'https://techcrunch.com/2023/04/13/chatgpt-spain-gdpr/',
    summary: 'In April 2023 the Spanish AEPD opened an ex officio investigation into OpenAI for possible GDPR breaches, following Italy\'s initial ChatGPT ban. The AEPD asked the European Data Protection Board to place ChatGPT on the plenary agenda, triggering the EDPB\'s ChatGPT Task Force. The investigation remains open with no final enforcement decision as of April 2026.',
    curriculum_relevance: 'Spain\'s move triggered the EDPB ChatGPT Task Force — important as the seed of the EU-wide coordinated approach. Useful to contrast with Italy\'s decisive enforcement.',
    citation: null,
  },

  // ── Australia ───────────────────────────────────────────────────────────────
  {
    case_name: 'Australian Information Commissioner v. Clearview AI',
    plaintiffs: ['Office of the Australian Information Commissioner (OAIC)'],
    defendants: ['Clearview AI, Inc.'],
    court: 'Office of the Australian Information Commissioner; Administrative Appeals Tribunal',
    judge: null,
    jurisdiction: 'Australia',
    district: 'OAIC determination; AAT review',
    circuit: null,
    status: 'decided',
    case_type: 'privacy',
    key_issues: [
      'Australian Privacy Principles 3.3 (sensitive / biometric info)',
      'facial recognition scraping',
      'extraterritorial reach of the Privacy Act 1988',
      'consent',
    ],
    filing_date: null,
    last_update: '2024-05-30',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: 'OAIC determination of 14 October 2021 found Clearview AI contravened the Privacy Act: collected biometric information from Australians without consent and failed to implement APP-compliant practices. Ordered Clearview to cease collecting Australian images and destroy existing data. AAT upheld the determination on 8 May 2023. In 2024 the Privacy Commissioner decided not to pursue further action, but the determination stands.',
    settlement_amount: null,
    case_url: 'https://www.oaic.gov.au/news/media-centre/clearview-ai-breached-australians-privacy',
    source_url: 'https://www.oaic.gov.au/news/media-centre/clearview-ai-breached-australians-privacy',
    summary: 'The OAIC issued a determination against Clearview AI in October 2021 for indiscriminate scraping of Australians\' facial images from the internet in breach of the Privacy Act and Australian Privacy Principles, including sensitive-information rules. Clearview appealed to the Administrative Appeals Tribunal, which confirmed the determination in May 2023 and made significant observations about the extraterritorial reach of the Privacy Act. In 2024 the Commissioner declined to take further enforcement action.',
    curriculum_relevance: 'One of the clearest precedents globally for regulating AI-driven biometric scraping. The AAT\'s extraterritorial analysis is directly relevant to how non-US AI providers will be held accountable under national law.',
    citation: null,
  },

  // ── Brazil ──────────────────────────────────────────────────────────────────
  {
    case_name: 'ANPD v. Meta (Brazil — AI training)',
    plaintiffs: ['Autoridade Nacional de Proteção de Dados (ANPD)'],
    defendants: ['Meta Platforms, Inc.'],
    court: 'Autoridade Nacional de Proteção de Dados',
    judge: null,
    jurisdiction: 'Brazil',
    district: 'Brazilian DPA',
    circuit: null,
    status: 'decided',
    case_type: 'privacy',
    key_issues: [
      'LGPD lawful basis (legitimate interests) for AI training',
      'transparency',
      'data subject rights / opt-out',
      'processing of minors\' data',
    ],
    filing_date: null,
    last_update: '2024-08-30',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: 'On 2 July 2024 the ANPD issued a preventive measure ordering Meta to suspend processing of Brazilian personal data for AI training, with potential fines of R$50,000/day for non-compliance. Meta initially suspended its genAI tools in Brazil, added Brazilian-language notices and opt-outs, and committed not to process minors\' data for AI training. On 30 August 2024 the ANPD lifted the preventive measure after compliance.',
    settlement_amount: null,
    case_url: null,
    source_url: 'https://fpf.org/blog/processing-of-personal-data-for-ai-training-in-brazil-takeaways-from-anpds-preliminary-decisions-in-the-meta-case/',
    summary: 'In July 2024 the Brazilian data protection authority (ANPD) issued a preventive measure suspending Meta\'s processing of Brazilian personal data for generative-AI training, citing risks under the LGPD including inadequate legal basis, lack of transparency, and insufficient protection for minors. Meta complied with disclosure, opt-out and child-data commitments, and the measure was lifted in August 2024 — one of the most concrete regulator-forced changes to a major AI company\'s practice.',
    curriculum_relevance: 'Demonstrates that Latin American data protection regulators can meaningfully force change at a global AI company. The LGPD framework is closely modelled on GDPR, making this case a strong comparator for EU enforcement.',
    citation: null,
  },

  // ── China ───────────────────────────────────────────────────────────────────
  {
    case_name: 'Li Yunkai v. Liu Yuanchun (Beijing Internet Court)',
    plaintiffs: ['Li Yunkai'],
    defendants: ['Liu Yuanchun'],
    court: 'Beijing Internet Court',
    judge: null,
    jurisdiction: 'China',
    district: 'Beijing Internet Court',
    circuit: null,
    status: 'decided',
    case_type: 'copyright',
    key_issues: [
      'copyrightability of AI-generated images',
      'originality and personalised expression',
      'obligation to disclose AI use',
      'Stable Diffusion outputs',
    ],
    filing_date: null,
    last_update: '2023-11-27',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: 'The Beijing Internet Court held that an image generated using Stable Diffusion was copyrightable. The court reasoned that the user\'s intellectual investment — selection and ordering of prompts, parameters and presentation — reflected personalised expression and originality sufficient for authorship. The defendant was ordered to apologise and pay damages. The court emphasised the obligation to disclose AI use.',
    settlement_amount: null,
    case_url: null,
    source_url: 'https://legalblogs.wolterskluwer.com/copyright-blog/beijing-internet-court-grants-copyright-to-ai-generated-image-for-the-first-time/',
    summary: 'On 27 November 2023 the Beijing Internet Court issued the first Chinese ruling on the copyrightability of AI-generated images in Li Yunkai v. Liu Yuanchun. The court held that a Stable Diffusion output, shaped by the user\'s prompt engineering and parameter choices, was a copyrightable work. The decision contrasts sharply with the US Copyright Office\'s position that prompted AI output is generally not copyrightable.',
    curriculum_relevance: 'The key non-Western precedent on AI copyrightability — directly opposite to the US Copyright Office\'s human-authorship position. Essential for any discussion of global divergence on AI-generated content.',
    citation: null,
  },

  // ── Ireland ─────────────────────────────────────────────────────────────────
  {
    case_name: 'DPC v. Twitter International Unlimited Company (Grok — Ireland)',
    plaintiffs: ['Data Protection Commission (DPC, Ireland)'],
    defendants: ['Twitter International Unlimited Company (X / xAI)'],
    court: 'High Court of Ireland',
    judge: null,
    jurisdiction: 'Ireland',
    district: 'Irish High Court',
    circuit: null,
    status: 'settled',
    case_type: 'privacy',
    key_issues: [
      'GDPR lawful basis for AI training on public posts',
      'Section 134 Data Protection Act 2018',
      'use of EU/EEA user data for Grok',
      'lead supervisory authority powers',
    ],
    filing_date: '2024-08-06',
    last_update: '2024-09-04',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: 'Proceedings concluded on 4 September 2024 with the High Court striking out the case on the basis of X\'s undertaking to permanently delete and not further process personal data from EU/EEA public posts used for training Grok between 7 May 2024 and 1 August 2024. First use of the DPC\'s s.134 powers.',
    settlement_amount: null,
    case_url: null,
    source_url: 'https://www.dataprotection.ie/en/news-media/press-releases/data-protection-commission-welcomes-conclusion-proceedings-relating-xs-ai-tool-grok',
    summary: 'On 6 August 2024 the Irish DPC launched proceedings in the High Court against Twitter International (TIUC), alleging that X\'s use of EU/EEA users\' public posts to train the Grok LLM breached GDPR. It was the first time any Lead Supervisory Authority had brought such an action, and the first use of the DPC\'s Section 134 powers. On 4 September 2024 the case was struck out after X gave a permanent undertaking to delete the training data and not repeat the practice.',
    curriculum_relevance: 'First urgent-court action by an EU Lead Supervisory Authority against an AI provider. Sets a precedent for how DPAs can move quickly to stop training-data ingestion before irreparable harm is done.',
    citation: null,
  },

  // ── Netherlands ─────────────────────────────────────────────────────────────
  {
    case_name: 'Autoriteit Persoonsgegevens v. Clearview AI (Netherlands)',
    plaintiffs: ['Autoriteit Persoonsgegevens (AP — Dutch DPA)'],
    defendants: ['Clearview AI, Inc.'],
    court: 'Autoriteit Persoonsgegevens',
    judge: null,
    jurisdiction: 'Netherlands',
    district: 'Dutch DPA',
    circuit: null,
    status: 'decided',
    case_type: 'privacy',
    key_issues: [
      'GDPR Art. 5(1) / 6(1) lawful basis',
      'GDPR Art. 9(1) special-category biometric data',
      'transparency obligations (Arts. 12, 14)',
      'facial recognition database',
      'extraterritorial enforcement',
    ],
    filing_date: null,
    last_update: '2024-09-03',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: 'On 16 May 2024 (announced publicly in September 2024) the Dutch DPA fined Clearview AI €30.5 million for processing Dutch residents\' personal and biometric data without lawful basis, and for failing to meet GDPR transparency obligations. Imposed four additional penalty orders with a further €5.1 million at stake for continued non-compliance. The Dutch DPA also said it was considering whether to hold Clearview executives personally liable.',
    settlement_amount: '€30,500,000',
    case_url: 'https://www.autoriteitpersoonsgegevens.nl/en/documents/decision-fine-clearview-ai',
    source_url: 'https://www.autoriteitpersoonsgegevens.nl/en/current/dutch-dpa-imposes-a-fine-on-clearview-because-of-illegal-data-collection-for-facial-recognition',
    summary: 'The Dutch DPA imposed a €30.5 million fine on Clearview AI for illegally building a facial-recognition database of Dutch residents in breach of GDPR. The fine was accompanied by four penalty orders (up to €5.1m additional) for continued non-compliance and unusual consideration of personal liability for executives — the largest GDPR fine yet imposed on Clearview.',
    curriculum_relevance: 'Notable for the size of the fine, the attempt to pierce the corporate veil, and the assertion of GDPR extraterritorial reach against a US-only-operating AI vendor.',
    citation: null,
  },

  // ── Japan ───────────────────────────────────────────────────────────────────
  {
    case_name: 'Yomiuri Shimbun v. Perplexity AI (Japan)',
    plaintiffs: ['The Yomiuri Shimbun Holdings'],
    defendants: ['Perplexity AI, Inc.'],
    court: 'Tokyo District Court',
    judge: null,
    jurisdiction: 'Japan',
    district: 'Tokyo District Court',
    circuit: null,
    status: 'active',
    case_type: 'copyright',
    key_issues: [
      'unauthorised reproduction of news articles by AI search',
      'Article 30-4 of Japan\'s Copyright Act (AI training exception)',
      'scraping and summarisation by Perplexity',
      'service of process on US AI provider',
    ],
    filing_date: '2025-08-07',
    last_update: '2025-08-07',
    next_deadline: null,
    next_deadline_notes: 'First ruling not expected for 12+ months given service on US HQ',
    outcome: null,
    settlement_amount: null,
    case_url: null,
    source_url: 'https://asia.nikkei.com/business/technology/artificial-intelligence/japanese-newspaper-yomiuri-sues-perplexity-ai-over-copyright',
    summary: 'Japan\'s largest newspaper, Yomiuri Shimbun, filed suit against Perplexity AI in the Tokyo District Court on 7 August 2025, alleging that Perplexity obtained and reproduced approximately 119,467 Yomiuri articles without permission between February and June 2025, reducing site traffic and ad revenue. Yomiuri seeks roughly $15 million in damages and an injunction. The first AI copyright lawsuit filed by a major Japanese media outlet.',
    curriculum_relevance: 'First major Japanese AI copyright case — tests the limits of Japan\'s pro-AI Article 30-4 training exception and whether AI search summarisation falls within or outside it. Essential for understanding the Japanese legal landscape.',
    citation: null,
  },

  {
    case_name: 'Nikkei and Asahi Shimbun v. Perplexity AI (Japan)',
    plaintiffs: ['Nikkei Inc.', 'The Asahi Shimbun Company'],
    defendants: ['Perplexity AI, Inc.'],
    court: 'Tokyo District Court',
    judge: null,
    jurisdiction: 'Japan',
    district: 'Tokyo District Court',
    circuit: null,
    status: 'active',
    case_type: 'copyright',
    key_issues: [
      'unauthorised adaptation of news articles',
      'misattribution of content to the plaintiffs',
      'Article 30-4 scope',
      'AI-search "free riding"',
    ],
    filing_date: '2025-08-26',
    last_update: '2025-08-26',
    next_deadline: null,
    next_deadline_notes: null,
    outcome: null,
    settlement_amount: null,
    case_url: null,
    source_url: 'https://www.japantimes.co.jp/news/2025/08/26/japan/crime-legal/japan-newspapers-sue-ai-startup/',
    summary: 'Nikkei and The Asahi Shimbun jointly filed suit against Perplexity AI in the Tokyo District Court on 26 August 2025, three weeks after Yomiuri filed a parallel action. Each seeks ¥2.2 billion (~$15 million) in damages and an injunction. The complaints cite "free riding" on the publishers\' news content and misattribution of inaccurate information.',
    curriculum_relevance: 'Second wave of Japanese AI copyright actions against Perplexity, confirming a coordinated industry response. Useful to discuss collective action by national publisher associations.',
    citation: null,
  },

  // ── Austria (noyb complaint) ────────────────────────────────────────────────
  {
    case_name: 'noyb complaint against OpenAI (ChatGPT hallucinations — Austria)',
    plaintiffs: ['noyb — European Center for Digital Rights'],
    defendants: ['OpenAI, L.L.C.'],
    court: 'Österreichische Datenschutzbehörde (DSB)',
    judge: null,
    jurisdiction: 'Austria',
    district: 'Austrian DPA',
    circuit: null,
    status: 'active',
    case_type: 'privacy',
    key_issues: [
      'GDPR Article 5(1)(d) accuracy of personal data',
      'right to rectification (Article 16)',
      'transparency about sources of data',
      'handling of subject access requests',
      'AI hallucinations as personal data',
    ],
    filing_date: '2024-04-29',
    last_update: '2025-03-19',
    next_deadline: null,
    next_deadline_notes: 'Follow-up complaint filed March 2025',
    outcome: null,
    settlement_amount: null,
    case_url: 'https://noyb.eu/sites/default/files/2024-04/OpenAI%20Complaint_EN_redacted.pdf',
    source_url: 'https://noyb.eu/en/chatgpt-provides-false-information-about-people-and-openai-cant-correct-it',
    summary: 'On 29 April 2024 noyb filed a GDPR complaint with the Austrian DSB on behalf of a public figure whom ChatGPT repeatedly assigned an incorrect date of birth and refused to correct. The complaint alleges violations of the GDPR accuracy principle, transparency obligations, and handling of subject access requests, and asks the DSB to order compliance and impose a fine. noyb filed a follow-on complaint in March 2025 over defamatory hallucinations.',
    curriculum_relevance: 'Raises the unresolved question of whether AI "hallucinations" about a person are personal data subject to the right of rectification, and whether an LLM provider can meaningfully comply with Article 16 GDPR at all. Central to the EU compliance debate.',
    citation: null,
  },
];

function coalesce(v) { return v === undefined ? null : v; }

async function run() {
  const client = await pool.connect();
  let inserted = 0;
  let skipped = 0;
  try {
    for (const c of CASES) {
      const sourceUrls = [c.source_url, c.case_url].filter(Boolean);
      const tags = ['ai-law', 'ai-litigation', c.case_type, c.jurisdiction.toLowerCase().replace(/\s+/g, '-')].filter(Boolean).slice(0, 10);

      const res = await client.query(
        `INSERT INTO ai_lawsuits
           (case_name, plaintiffs, defendants, court, judge, jurisdiction, district, circuit,
            status, case_type, key_issues, filing_date, last_update, next_deadline, next_deadline_notes,
            outcome, settlement_amount, case_url, source_url, source_urls,
            summary, curriculum_relevance, is_curriculum_relevant, tags)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24)
         ON CONFLICT (case_name) DO NOTHING
         RETURNING id`,
        [
          c.case_name,
          c.plaintiffs || [],
          c.defendants || [],
          coalesce(c.court),
          coalesce(c.judge),
          c.jurisdiction,
          coalesce(c.district),
          coalesce(c.circuit),
          c.status || 'active',
          c.case_type || 'copyright',
          c.key_issues || [],
          coalesce(c.filing_date),
          coalesce(c.last_update),
          coalesce(c.next_deadline),
          coalesce(c.next_deadline_notes),
          coalesce(c.outcome),
          coalesce(c.settlement_amount),
          coalesce(c.case_url),
          coalesce(c.source_url),
          sourceUrls,
          coalesce(c.summary),
          coalesce(c.curriculum_relevance),
          true,
          tags,
        ]
      );
      if (res.rowCount > 0) {
        inserted += 1;
        console.log(`  inserted: ${c.case_name} (${c.jurisdiction})`);
      } else {
        skipped += 1;
        console.log(`  skipped (already exists): ${c.case_name}`);
      }
    }
    console.log(`\nDone. Inserted ${inserted}, skipped ${skipped}, total input ${CASES.length}.`);
  } finally {
    client.release();
    await pool.end();
  }
}

run().catch(err => { console.error(err); process.exit(1); });
