// Seed: global AI regulations.
//
// Each entry has been verified (April 2026) against an official source and at
// least one independent explainer. Dates are taken from primary sources where
// possible; left NULL where public record is ambiguous. Safe to re-run:
// ON CONFLICT (short_name, jurisdiction) DO NOTHING.
//
// Run: node server/db/scripts/seed_global_regulations.js

import pool from '../pool.js';

const REGS = [
  // ── EU ──────────────────────────────────────────────────────────────────────
  {
    regulation_name: 'Regulation (EU) 2024/1689 of the European Parliament and of the Council laying down harmonised rules on artificial intelligence (Artificial Intelligence Act)',
    short_name: 'EU AI Act',
    jurisdiction: 'EU',
    regulator: 'European Commission (AI Office); national competent authorities',
    status: 'partial_force',
    regulation_type: 'regulation',
    scope: ['general-purpose AI', 'high-risk AI', 'prohibited AI practices', 'foundation models', 'biometric systems'],
    affected_sectors: ['all sectors deploying AI', 'providers', 'deployers', 'importers', 'distributors'],
    proposed_date: '2021-04-21',
    enacted_date: '2024-06-13',
    effective_date: '2024-08-01',
    enforcement_date: '2025-08-02',
    next_milestone: '2026-08-02',
    next_milestone_notes: 'Full applicability of high-risk AI system rules on 2 Aug 2026; product-embedded AI rules 2 Aug 2027.',
    key_provisions: [
      'Risk-tiered framework: unacceptable / high-risk / limited-risk / minimal-risk',
      'Prohibited practices (social scoring, manipulative AI, real-time remote biometric ID in public) from 2 Feb 2025',
      'AI literacy obligations from 2 Feb 2025',
      'General-purpose AI (GPAI) transparency + copyright policy + technical documentation from 2 Aug 2025',
      'Systemic-risk GPAI: model evaluation, adversarial testing, incident reporting, cybersecurity',
      'High-risk AI: risk management, data governance, logging, human oversight, conformity assessment, EU database registration (from 2 Aug 2026)',
      'Transparency obligations for generative AI outputs / deepfakes',
    ],
    penalties: 'Up to €35 million or 7% of global annual turnover (whichever higher) for prohibited-practice infringements; €15M / 3% for GPAI obligations; €7.5M / 1.5% for supplying incorrect information.',
    extraterritorial_scope: 'Applies to providers established outside the EU who place AI systems on the EU market or whose output is used in the EU; to deployers in the EU; and to importers/distributors regardless of establishment.',
    official_url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    source_url: 'https://artificialintelligenceact.eu/implementation-timeline/',
    summary: 'The world\'s first comprehensive horizontal AI law. Entered into force 1 August 2024 with a phased application: prohibited practices and AI literacy from February 2025, GPAI transparency and the penalty regime from August 2025, high-risk-system rules from August 2026. Risk-tiered, extraterritorial in scope, and the reference point for most other jurisdictions now drafting AI law.',
    curriculum_relevance: 'The single most important AI regulation globally and the baseline every multinational AI vendor must comply with. Essential for every media and AI-ethics curriculum.',
    tags: ['eu', 'horizontal', 'risk-tiered', 'gpai', 'extraterritorial'],
  },

  {
    regulation_name: 'Regulation (EU) 2016/679 — General Data Protection Regulation',
    short_name: 'GDPR',
    jurisdiction: 'EU',
    regulator: 'National Data Protection Authorities; European Data Protection Board (EDPB)',
    status: 'in_force',
    regulation_type: 'regulation',
    scope: ['processing of personal data', 'AI training data', 'automated decision-making'],
    affected_sectors: ['all sectors processing personal data of EU residents'],
    proposed_date: null,
    enacted_date: '2016-04-27',
    effective_date: '2018-05-25',
    enforcement_date: '2018-05-25',
    next_milestone: null,
    next_milestone_notes: null,
    key_provisions: [
      'Article 5 — accuracy, lawfulness, fairness, transparency',
      'Article 6 — lawful basis for processing (including training data)',
      'Article 9 — special category data (biometrics)',
      'Article 16 — right to rectification (problematic for LLM hallucinations)',
      'Article 22 — restrictions on solely automated decision-making with significant effects',
      'Articles 12–14 — transparency and information obligations',
      'Chapter V — restrictions on international data transfers',
    ],
    penalties: 'Up to €20 million or 4% of global annual turnover (higher tier); €10M / 2% (lower tier).',
    extraterritorial_scope: 'Applies to controllers/processors outside the EU offering goods or services to, or monitoring, EU data subjects (Art. 3(2)).',
    official_url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
    source_url: 'https://gdpr-info.eu/',
    summary: 'The foundation of EU data protection law. Every major European enforcement action against AI providers (Garante v. OpenAI, DPC v. X/Grok, Dutch DPA v. Clearview) has been built on GDPR. Articles 5, 6, 16 and 22 are directly implicated by AI training and output.',
    curriculum_relevance: 'You cannot understand EU AI enforcement without GDPR. The EDPB\'s ChatGPT Task Force, the Garante fines, and the Clearview fines all rest on it.',
    tags: ['eu', 'privacy', 'extraterritorial', 'foundational'],
  },

  {
    regulation_name: 'Regulation (EU) 2022/2065 — Digital Services Act',
    short_name: 'DSA',
    jurisdiction: 'EU',
    regulator: 'European Commission (for VLOPs/VLOSEs); Digital Services Coordinators',
    status: 'in_force',
    regulation_type: 'regulation',
    scope: ['online intermediaries', 'platforms', 'AI content moderation', 'AI-generated content labelling'],
    affected_sectors: ['online platforms', 'search engines', 'hosting services', 'very large online platforms (VLOPs)'],
    proposed_date: null,
    enacted_date: '2022-10-19',
    effective_date: '2024-02-17',
    enforcement_date: '2024-02-17',
    next_milestone: null,
    next_milestone_notes: 'Ongoing VLOP/VLOSE designations and investigations',
    key_provisions: [
      'Risk assessment and mitigation obligations for VLOPs/VLOSEs, including AI-driven systemic risks',
      'Transparency of recommender systems and content moderation',
      'Labelling of AI-generated or manipulated content (deepfakes)',
      'Trusted flagger and notice-and-action regimes',
      'Researcher and regulator access to platform data',
    ],
    penalties: 'Up to 6% of global annual turnover for VLOPs/VLOSEs.',
    extraterritorial_scope: 'Applies to intermediary services offered to EU users regardless of establishment.',
    official_url: 'https://eur-lex.europa.eu/eli/reg/2022/2065/oj',
    source_url: 'https://digital-strategy.ec.europa.eu/en/policies/digital-services-act-package',
    summary: 'The EU\'s platform-governance regime — directly engages AI in recommender systems, content moderation, and AI-generated content labelling. Interacts with the AI Act for VLOPs deploying generative AI.',
    curriculum_relevance: 'Critical for media and platform professionals: governs how AI-generated content must be labelled and how platforms must assess and mitigate AI-driven systemic risks.',
    tags: ['eu', 'platforms', 'content-moderation', 'deepfakes'],
  },

  {
    regulation_name: 'Regulation (EU) 2022/1925 — Digital Markets Act',
    short_name: 'DMA',
    jurisdiction: 'EU',
    regulator: 'European Commission',
    status: 'in_force',
    regulation_type: 'regulation',
    scope: ['digital gatekeepers', 'core platform services', 'AI integration in gatekeeper services'],
    affected_sectors: ['designated gatekeepers: Alphabet, Amazon, Apple, ByteDance, Meta, Microsoft, Booking'],
    proposed_date: null,
    enacted_date: '2022-09-14',
    effective_date: '2023-05-02',
    enforcement_date: '2024-03-07',
    next_milestone: null,
    next_milestone_notes: null,
    key_provisions: [
      'Gatekeeper designation and core platform service obligations',
      'Restrictions on self-preferencing and tying of AI products',
      'Interoperability and data portability',
      'Prohibition on using business-user data to compete against them',
    ],
    penalties: 'Up to 10% of global annual turnover; up to 20% for repeat infringements; periodic penalty payments up to 5% of average daily turnover.',
    extraterritorial_scope: 'Applies to any designated gatekeeper offering core platform services in the EU regardless of establishment.',
    official_url: 'https://eur-lex.europa.eu/eli/reg/2022/1925/oj',
    source_url: 'https://digital-markets-act.ec.europa.eu/',
    summary: 'Ex-ante competition regulation for digital gatekeepers. Increasingly relevant as gatekeepers integrate AI assistants, search and recommender systems across their stacks.',
    curriculum_relevance: 'Important framing for AI competition questions: how far can Big Tech integrate AI features into gatekeeper services before triggering DMA obligations?',
    tags: ['eu', 'competition', 'gatekeepers'],
  },

  // ── United Kingdom ──────────────────────────────────────────────────────────
  {
    regulation_name: 'A pro-innovation approach to AI regulation (UK AI White Paper)',
    short_name: 'UK AI White Paper',
    jurisdiction: 'UK',
    regulator: 'Department for Science, Innovation and Technology (DSIT)',
    status: 'in_force',
    regulation_type: 'guidance',
    scope: ['all AI systems', 'sectoral regulator-led approach'],
    affected_sectors: ['all sectors — each under its own existing regulator (ICO, CMA, FCA, MHRA, Ofcom, etc.)'],
    proposed_date: '2023-03-29',
    enacted_date: null,
    effective_date: null,
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'New Labour government has signalled an AI bill but none enacted as of April 2026',
    key_provisions: [
      'Five cross-sector principles: safety, transparency, fairness, accountability, contestability',
      'No new horizontal AI statute; existing regulators apply the principles in their domains',
      'AI Safety Institute (AISI) focus on frontier-model evaluation',
      'Voluntary commitments from frontier labs',
    ],
    penalties: 'Sector-specific (via existing regulator powers).',
    extraterritorial_scope: 'Principles are non-binding; extraterritorial reach is via sectoral law (e.g. UK GDPR).',
    official_url: 'https://www.gov.uk/government/publications/ai-regulation-a-pro-innovation-approach',
    source_url: 'https://www.gov.uk/government/publications/ai-regulation-a-pro-innovation-approach',
    summary: 'The UK\'s deliberately light-touch, sector-regulator-led AI approach — a conscious contrast to the EU AI Act. Focused on principles + the AI Safety Institute for frontier models rather than comprehensive statute.',
    curriculum_relevance: 'Illustrates the main philosophical alternative to the EU approach. Understanding this framing is essential for any discussion of global AI regulatory divergence.',
    tags: ['uk', 'principles-based', 'sectoral'],
  },

  {
    regulation_name: 'Online Safety Act 2023',
    short_name: 'Online Safety Act',
    jurisdiction: 'UK',
    regulator: 'Ofcom',
    status: 'in_force',
    regulation_type: 'statute',
    scope: ['user-to-user services', 'search services', 'AI-generated harmful content', 'deepfake intimate imagery'],
    affected_sectors: ['social media', 'search', 'user-generated content platforms'],
    proposed_date: null,
    enacted_date: '2023-10-26',
    effective_date: '2023-10-26',
    enforcement_date: '2025-03-17',
    next_milestone: null,
    next_milestone_notes: 'Phased Ofcom codes of practice through 2025–2026',
    key_provisions: [
      'Duties of care on in-scope services re: illegal content and (for Category 1) legal-but-harmful content',
      'Specific offences including sharing AI-generated intimate images without consent',
      'Age assurance for pornographic content (including AI-generated)',
      'Ofcom codes of practice and transparency reports',
    ],
    penalties: 'Up to £18 million or 10% of qualifying worldwide revenue, whichever higher; business disruption measures; senior manager liability.',
    extraterritorial_scope: 'Applies to services with links to the UK (UK users or significant number of UK users) regardless of establishment.',
    official_url: 'https://www.legislation.gov.uk/ukpga/2023/50',
    source_url: 'https://www.ofcom.org.uk/online-safety',
    summary: 'The UK\'s flagship platform-safety statute. Includes AI-specific offences (synthetic intimate imagery) and treats AI-generated harmful content within the same duty-of-care framework as user-generated content.',
    curriculum_relevance: 'Key for UK media and platform curricula — the statutory home of AI-content-moderation and synthetic-media obligations in the UK.',
    tags: ['uk', 'platforms', 'deepfakes', 'content-moderation'],
  },

  // ── United States (federal) ─────────────────────────────────────────────────
  {
    regulation_name: 'Executive Order 14110 on the Safe, Secure, and Trustworthy Development and Use of Artificial Intelligence',
    short_name: 'EO 14110 (Biden AI EO)',
    jurisdiction: 'US Federal',
    regulator: 'White House; agencies (NIST, OMB, DHS, etc.)',
    status: 'repealed',
    regulation_type: 'executive_order',
    scope: ['federal agency AI use', 'frontier model reporting', 'critical infrastructure AI'],
    affected_sectors: ['federal government', 'frontier AI developers meeting compute threshold', 'critical infrastructure'],
    proposed_date: null,
    enacted_date: '2023-10-30',
    effective_date: '2023-10-30',
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Revoked 20 January 2025 by Executive Order 14179 of the Trump administration',
    key_provisions: [
      'Defense Production Act reporting for frontier models over compute thresholds',
      'Agency-wide AI governance, chief AI officers',
      'NIST AI safety standards development',
      'Watermarking and provenance research',
      'Workforce, civil rights and consumer-protection directives',
    ],
    penalties: 'None (directive to federal agencies).',
    extraterritorial_scope: 'Not extraterritorial.',
    official_url: 'https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence',
    source_url: 'https://www.whitehouse.gov/briefing-room/presidential-actions/2023/10/30/executive-order-on-the-safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence/',
    summary: 'The Biden administration\'s landmark AI executive order, issued October 2023. Revoked by the Trump administration via EO 14179 on 20 January 2025. While the order itself is no longer in force, the NIST workstreams and agency AI governance structures it established largely persist.',
    curriculum_relevance: 'Essential historical context — the high-water mark of US federal AI policy ambition, its rapid reversal illustrates US political volatility on AI.',
    tags: ['us', 'federal', 'executive-order', 'repealed'],
  },

  {
    regulation_name: 'NIST AI Risk Management Framework 1.0 (AI RMF) and Generative AI Profile',
    short_name: 'NIST AI RMF',
    jurisdiction: 'US Federal',
    regulator: 'National Institute of Standards and Technology (NIST)',
    status: 'in_force',
    regulation_type: 'standard',
    scope: ['AI systems generally', 'generative AI'],
    affected_sectors: ['voluntary adoption across all sectors; often referenced in government procurement and regulations'],
    proposed_date: null,
    enacted_date: '2023-01-26',
    effective_date: '2023-01-26',
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Generative AI Profile (NIST AI 600-1) published 26 July 2024',
    key_provisions: [
      'Four core functions: Govern, Map, Measure, Manage',
      'AI RMF Playbook and Roadmap for practical implementation',
      'Generative AI Profile addresses hallucinations, confabulation, CBRN risks, data privacy, copyright, human-AI interaction',
    ],
    penalties: 'Voluntary — not legally enforceable in itself, but incorporated by reference into procurement, insurance and sectoral rules.',
    extraterritorial_scope: 'Voluntary global adoption.',
    official_url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    source_url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    summary: 'The de-facto US reference framework for AI risk management. Voluntary, but functions as a common baseline: referenced by state laws, federal procurement, insurance underwriting, and many jurisdictions abroad.',
    curriculum_relevance: 'The most-cited voluntary framework in English-speaking AI governance. Students should know Govern/Map/Measure/Manage structure and where the GenAI Profile differs.',
    tags: ['us', 'voluntary', 'standard', 'genai'],
  },

  // ── United States (state) ───────────────────────────────────────────────────
  {
    regulation_name: 'Colorado Senate Bill 24-205 — Consumer Protections for Artificial Intelligence (Colorado AI Act)',
    short_name: 'Colorado AI Act',
    jurisdiction: 'US State — Colorado',
    regulator: 'Colorado Attorney General',
    status: 'enacted',
    regulation_type: 'statute',
    scope: ['high-risk AI systems', 'consequential decisions', 'algorithmic discrimination'],
    affected_sectors: ['employment', 'education', 'financial services', 'government services', 'healthcare', 'housing', 'insurance', 'legal services'],
    proposed_date: null,
    enacted_date: '2024-05-17',
    effective_date: '2026-06-30',
    enforcement_date: '2026-06-30',
    next_milestone: '2026-06-30',
    next_milestone_notes: 'Effective date postponed from 1 Feb 2026 to 30 Jun 2026 by SB 25B-004 signed 28 Aug 2025',
    key_provisions: [
      'Developers and deployers of high-risk AI must use reasonable care to prevent algorithmic discrimination',
      'Impact assessments for high-risk systems',
      'Consumer notice and disclosure obligations',
      'Affirmative defense for adherence to a recognised risk management framework',
      'AG exclusive enforcement; treated as a deceptive trade practice under the Colorado Consumer Protection Act',
    ],
    penalties: 'Enforced as deceptive trade practice under the Colorado Consumer Protection Act — fines and injunctions.',
    extraterritorial_scope: 'Applies to developers and deployers doing business in Colorado.',
    official_url: 'https://leg.colorado.gov/bills/sb24-205',
    source_url: 'https://www.akingump.com/en/insights/ai-law-and-regulation-tracker/colorado-postpones-implementation-of-colorado-ai-act-sb-24-205',
    summary: 'The first US state comprehensive AI anti-discrimination statute. Structurally similar to the EU AI Act\'s high-risk-system regime. Effective date was postponed in August 2025 from 1 Feb 2026 to 30 Jun 2026 to allow more rulemaking.',
    curriculum_relevance: 'The US state bellwether for high-risk-AI regulation. Essential for anyone advising a US-operating AI developer or deployer.',
    tags: ['us', 'state', 'colorado', 'high-risk', 'anti-discrimination'],
  },

  {
    regulation_name: 'California Assembly Bill 2013 — Generative artificial intelligence: training data transparency',
    short_name: 'California AB 2013',
    jurisdiction: 'US State — California',
    regulator: 'California Attorney General',
    status: 'enacted',
    regulation_type: 'statute',
    scope: ['generative AI training data disclosure'],
    affected_sectors: ['generative AI developers making systems available to Californians'],
    proposed_date: null,
    enacted_date: '2024-09-28',
    effective_date: '2026-01-01',
    enforcement_date: '2026-01-01',
    next_milestone: '2026-01-01',
    next_milestone_notes: 'Disclosure due on or before 1 Jan 2026 for systems made available since 1 Jan 2022',
    key_provisions: [
      'Developers must post on their website documentation describing datasets used to train each GenAI system or service',
      'Covers sources, whether data includes personal information, data collection period, provenance, and purchased/licensed data',
      'Applies to substantial modifications as well as new releases',
    ],
    penalties: 'No specific fine; enforceable by California AG under existing consumer-protection law.',
    extraterritorial_scope: 'Applies to developers making GenAI systems available to Californians.',
    official_url: 'https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202320240AB2013',
    source_url: 'https://www.goodwinlaw.com/en/insights/publications/2025/06/alerts-ai-californias-ab-2013-generative-ai-developers-show-their-data',
    summary: 'Requires public, detailed disclosures of GenAI training data. Signed by Gov. Newsom on 28 September 2024 and takes effect 1 January 2026 — the first US training-data-transparency law.',
    curriculum_relevance: 'The California training-data-transparency experiment is the closest US analogue to the EU AI Act\'s GPAI transparency rules. Essential for any AI-industry student.',
    tags: ['us', 'state', 'california', 'training-data', 'transparency'],
  },

  {
    regulation_name: 'Texas House Bill 149 — Texas Responsible Artificial Intelligence Governance Act (TRAIGA)',
    short_name: 'Texas TRAIGA',
    jurisdiction: 'US State — Texas',
    regulator: 'Texas Attorney General',
    status: 'enacted',
    regulation_type: 'statute',
    scope: ['AI developers and deployers', 'prohibited practices (social scoring, unlawful discrimination)'],
    affected_sectors: ['all sectors deploying AI in Texas'],
    proposed_date: null,
    enacted_date: '2025-06-22',
    effective_date: '2026-01-01',
    enforcement_date: '2026-01-01',
    next_milestone: '2026-01-01',
    next_milestone_notes: null,
    key_provisions: [
      'Baseline duties for developers and deployers',
      'Prohibition on AI intended for social scoring or unlawful discrimination',
      'First-in-US AI regulatory sandbox',
      'Exclusive enforcement by the Texas Attorney General',
    ],
    penalties: 'Attorney General civil actions; injunctive relief and civil penalties.',
    extraterritorial_scope: 'Applies to conduct affecting Texas residents.',
    official_url: 'https://capitol.texas.gov/BillLookup/History.aspx?LegSess=89R&Bill=HB149',
    source_url: 'https://www.klgates.com/Pared-Back-Version-of-the-Texas-Responsible-Artificial-Intelligence-Governance-Act-Signed-Into-Law-6-24-2025',
    summary: 'Texas\' pared-back AI governance law (originally HB 1709 / TRAIGA 1.0, enacted in simpler form as HB 149 / TRAIGA 2.0). Signed 22 June 2025 by Gov. Abbott. Effective 1 January 2026. Third US state after Colorado and Utah.',
    curriculum_relevance: 'Illustrates how US state AI law is evolving — Texas\' version is narrower than the original proposal and notably adds an AI regulatory sandbox.',
    tags: ['us', 'state', 'texas', 'sandbox'],
  },

  {
    regulation_name: 'New York City Local Law 144 — Automated Employment Decision Tools',
    short_name: 'NYC Local Law 144',
    jurisdiction: 'US State — New York',
    regulator: 'NYC Department of Consumer and Worker Protection',
    status: 'in_force',
    regulation_type: 'statute',
    scope: ['automated employment decision tools (AEDTs)', 'hiring and promotion'],
    affected_sectors: ['employment'],
    proposed_date: null,
    enacted_date: '2021-12-11',
    effective_date: '2023-07-05',
    enforcement_date: '2023-07-05',
    next_milestone: null,
    next_milestone_notes: null,
    key_provisions: [
      'Mandatory annual independent bias audit of AEDTs',
      'Public summary of audit results',
      'Notice to candidates and employees before use',
      'Disclosure of the job qualifications and characteristics the AEDT uses',
    ],
    penalties: 'USD 500 for first violation; USD 500–1,500 per violation thereafter (per day, per candidate).',
    extraterritorial_scope: 'Applies to use of AEDTs for employment decisions in NYC.',
    official_url: 'https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page',
    source_url: 'https://www.nyc.gov/site/dca/about/automated-employment-decision-tools.page',
    summary: 'The first US municipal law to require independent bias audits for AI-driven hiring tools. Despite comparatively low penalties it is heavily cited as a regulatory prototype.',
    curriculum_relevance: 'Widely studied municipal experiment — illustrates what "bias audit" requirements look like in statute, and the enforcement practicalities.',
    tags: ['us', 'state', 'nyc', 'employment', 'bias-audit'],
  },

  {
    regulation_name: 'Illinois Biometric Information Privacy Act (740 ILCS 14/)',
    short_name: 'Illinois BIPA',
    jurisdiction: 'US State — Illinois',
    regulator: 'Private right of action (no state regulator)',
    status: 'in_force',
    regulation_type: 'statute',
    scope: ['biometric identifiers and information', 'facial recognition', 'voiceprints'],
    affected_sectors: ['any private entity collecting biometric data of Illinois residents'],
    proposed_date: null,
    enacted_date: '2008-10-03',
    effective_date: '2008-10-03',
    enforcement_date: '2008-10-03',
    next_milestone: null,
    next_milestone_notes: 'Amended 2 Aug 2024 (SB 2979) to limit per-scan damages aggregation',
    key_provisions: [
      'Written notice and consent before collecting biometric identifiers',
      'Public retention and destruction policies',
      'Ban on sale of biometric data',
      'Private right of action with statutory damages (USD 1,000 negligent; USD 5,000 intentional or reckless, per violation — post-2024 amendment, per person rather than per scan)',
    ],
    penalties: 'Statutory damages per violation; attorney\'s fees. Has produced the largest privacy settlements in US history (Facebook USD 650m, Google USD 100m, Snapchat USD 35m).',
    extraterritorial_scope: 'Applies to collection of Illinois residents\' biometric data regardless of company location.',
    official_url: 'https://www.ilga.gov/legislation/ilcs/ilcs3.asp?ActID=3004',
    source_url: 'https://www.eff.org/issues/biometrics',
    summary: 'Although pre-AI, BIPA is the most-litigated privacy statute for AI facial recognition and biometric systems in the US. The 2024 amendment capped aggregated damages but did not weaken the core notice/consent regime.',
    curriculum_relevance: 'Essential for any US AI facial-recognition curriculum — BIPA is where most of the big class actions happen and where the case law on biometric consent has been built.',
    tags: ['us', 'state', 'illinois', 'biometrics', 'private-right-of-action'],
  },

  // ── China ───────────────────────────────────────────────────────────────────
  {
    regulation_name: 'Interim Measures for the Management of Generative Artificial Intelligence Services',
    short_name: 'China Generative AI Measures',
    jurisdiction: 'China',
    regulator: 'Cyberspace Administration of China (CAC) and six co-issuing agencies',
    status: 'in_force',
    regulation_type: 'regulation',
    scope: ['generative AI services provided to the Chinese public'],
    affected_sectors: ['consumer-facing GenAI providers'],
    proposed_date: null,
    enacted_date: '2023-07-13',
    effective_date: '2023-08-15',
    enforcement_date: '2023-08-15',
    next_milestone: null,
    next_milestone_notes: null,
    key_provisions: [
      'Algorithm and security assessments before public launch',
      'Training-data lawfulness and IP compliance requirements',
      'Labelling of synthetic content',
      'Content must "adhere to core socialist values" and comply with the internet content regime',
      'Provider real-name verification and personal information protection',
    ],
    penalties: 'Warnings, rectification orders, suspension of services, fines; criminal referral for serious cases.',
    extraterritorial_scope: 'Applies to services provided to users within mainland China.',
    official_url: 'http://www.cac.gov.cn/2023-07/13/c_1690898327029107.htm',
    source_url: 'https://digichina.stanford.edu/work/translation-measures-for-the-management-of-generative-artificial-intelligence-services-effective-august-15-2023/',
    summary: 'The world\'s first national binding rules for generative AI services. Effective 15 August 2023. Providers must undergo security review, label synthetic content, and ensure training data and outputs comply with Chinese content rules.',
    curriculum_relevance: 'The comparator everyone cites when contrasting EU and US approaches with "China\'s approach". Essential reading.',
    tags: ['china', 'genai', 'content-control'],
  },

  {
    regulation_name: 'Provisions on the Administration of Deep Synthesis Internet Information Services',
    short_name: 'China Deep Synthesis Provisions',
    jurisdiction: 'China',
    regulator: 'Cyberspace Administration of China (CAC); Ministry of Industry and Information Technology; Ministry of Public Security',
    status: 'in_force',
    regulation_type: 'regulation',
    scope: ['deep synthesis services (deepfakes, voice cloning, AI-generated media)'],
    affected_sectors: ['platforms offering synthetic media services'],
    proposed_date: null,
    enacted_date: '2022-11-25',
    effective_date: '2023-01-10',
    enforcement_date: '2023-01-10',
    next_milestone: null,
    next_milestone_notes: null,
    key_provisions: [
      'Conspicuous labelling of deep-synthesis content',
      'Watermarking and traceability requirements',
      'Consent for synthesising a person\'s image/voice',
      'Filing and security assessment obligations',
    ],
    penalties: 'Administrative penalties including fines and service suspension; criminal referral.',
    extraterritorial_scope: 'Applies to services provided to users within China.',
    official_url: 'http://www.cac.gov.cn/2022-12/11/c_1672221949354811.htm',
    source_url: 'https://digichina.stanford.edu/work/translation-provisions-on-the-administration-of-deep-synthesis-internet-information-services-effective-jan-10-2023/',
    summary: 'Effective 10 January 2023 — the world\'s first comprehensive binding deepfake regulation. Requires conspicuous labelling, watermarking, and consent for synthetic representations of individuals.',
    curriculum_relevance: 'The global benchmark for deepfake rules. Essential for any media or platform curriculum.',
    tags: ['china', 'deepfakes', 'synthetic-media', 'labelling'],
  },

  {
    regulation_name: 'Personal Information Protection Law of the People\'s Republic of China',
    short_name: 'PIPL',
    jurisdiction: 'China',
    regulator: 'Cyberspace Administration of China (CAC); other sectoral authorities',
    status: 'in_force',
    regulation_type: 'statute',
    scope: ['personal information processing', 'AI training data', 'automated decision-making'],
    affected_sectors: ['all sectors processing personal information of PRC residents'],
    proposed_date: null,
    enacted_date: '2021-08-20',
    effective_date: '2021-11-01',
    enforcement_date: '2021-11-01',
    next_milestone: null,
    next_milestone_notes: null,
    key_provisions: [
      'Consent and separate-consent regimes for sensitive information and cross-border transfers',
      'Automated decision-making transparency and opt-out rights',
      'Cross-border data transfer mechanisms (CAC security assessment, standard contract, certification)',
      'Extraterritorial application',
    ],
    penalties: 'Up to RMB 50 million or 5% of annual turnover; personal fines on responsible individuals up to RMB 1 million.',
    extraterritorial_scope: 'Applies to processing outside China of PRC residents\' personal information if for providing products/services to them or analysing their behaviour.',
    official_url: 'http://www.npc.gov.cn/npc/c2/c30834/202108/t20210820_313088.html',
    source_url: 'https://digichina.stanford.edu/work/translation-personal-information-protection-law-of-the-peoples-republic-of-china-effective-nov-1-2021/',
    summary: 'China\'s GDPR-equivalent comprehensive data protection law. Includes explicit automated-decision-making rights that directly apply to AI systems using personal information.',
    curriculum_relevance: 'Parallel to GDPR — anyone operating AI at scale in China must master PIPL\'s cross-border transfer and consent regime.',
    tags: ['china', 'privacy', 'extraterritorial'],
  },

  // ── Canada ──────────────────────────────────────────────────────────────────
  {
    regulation_name: 'Artificial Intelligence and Data Act (Bill C-27 Part 3)',
    short_name: 'AIDA (Canada)',
    jurisdiction: 'Canada',
    regulator: 'Innovation, Science and Economic Development Canada (ISED) — proposed AI and Data Commissioner',
    status: 'repealed',
    regulation_type: 'statute',
    scope: ['high-impact AI systems', 'general-purpose AI systems'],
    affected_sectors: ['all sectors deploying high-impact AI'],
    proposed_date: '2022-06-16',
    enacted_date: null,
    effective_date: null,
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Bill C-27 died at prorogation on 6 January 2025; in June 2025 Minister Evan Solomon confirmed AIDA would not return in its original form',
    key_provisions: [
      'Obligations on persons responsible for high-impact AI systems',
      'Prohibitions on making AI systems available with knowledge of serious harm',
      'Record-keeping, risk assessment, transparency obligations',
      'Criminal offences for reckless development',
    ],
    penalties: 'Proposed administrative monetary penalties and criminal penalties up to CAD 25 million or 5% of global revenue.',
    extraterritorial_scope: 'Proposed to apply to regulated AI activities affecting Canada.',
    official_url: 'https://www.parl.ca/legisinfo/en/bill/44-1/c-27',
    source_url: 'https://www.fasken.com/en/knowledge/2025/01/prorogations-digital-impact',
    summary: 'Canada\'s first comprehensive AI statute proposal, introduced as part of Bill C-27. Died when Parliament was prorogued on 6 January 2025; the government has indicated any future AI law will be a fresh framework rather than AIDA reintroduced.',
    curriculum_relevance: 'A cautionary case study in AI legislation: an ambitious proposal that lost political momentum. Useful for discussions of AI regulation as a political process.',
    tags: ['canada', 'repealed', 'failed-bill'],
  },

  // ── Brazil ──────────────────────────────────────────────────────────────────
  {
    regulation_name: 'Brazil Senate Bill PL 2338/2023 on Artificial Intelligence',
    short_name: 'Brazil AI Bill (PL 2338/2023)',
    jurisdiction: 'Brazil',
    regulator: 'Proposed: ANPD + sectoral regulators; coordinating AI authority to be designated',
    status: 'proposed',
    regulation_type: 'statute',
    scope: ['risk-tiered AI regulation', 'high-risk AI systems', 'GenAI'],
    affected_sectors: ['all sectors deploying AI in Brazil'],
    proposed_date: '2023-05-03',
    enacted_date: null,
    effective_date: null,
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Senate approved 10 Dec 2024; in Chamber of Deputies special committee since April 2025; no expected vote date as of April 2026',
    key_provisions: [
      'Risk-tiered structure similar to EU AI Act (prohibited, high-risk, other)',
      'Rights-based framework including right to explanation and non-discrimination',
      'Copyright and training-data provisions (a contested point)',
      'AI regulatory authority to be designated',
    ],
    penalties: 'Proposed administrative fines up to BRL 50 million or 2% of Brazilian turnover per infringement.',
    extraterritorial_scope: 'Proposed to apply to AI activities with effects in Brazil.',
    official_url: 'https://www25.senado.leg.br/web/atividade/materias/-/materia/157233',
    source_url: 'https://www.loc.gov/item/global-legal-monitor/2025-05-23/brazil-senate-advances-discussions-on-bill-to-regulate-ai-use/',
    summary: 'Brazil\'s flagship AI bill. Passed the Senate on 10 December 2024 and is in the Chamber of Deputies (special committee since April 2025). Modelled on the EU AI Act but with stronger rights-based and copyright provisions.',
    curriculum_relevance: 'The Latin American version of the EU AI Act. Important for students to see how a major emerging market is adapting the risk-tier approach.',
    tags: ['brazil', 'proposed', 'risk-tiered'],
  },

  // ── India ───────────────────────────────────────────────────────────────────
  {
    regulation_name: 'Digital Personal Data Protection Act, 2023',
    short_name: 'DPDP Act 2023',
    jurisdiction: 'India',
    regulator: 'Data Protection Board of India (to be constituted)',
    status: 'enacted',
    regulation_type: 'statute',
    scope: ['processing of digital personal data', 'AI training using personal data'],
    affected_sectors: ['all sectors processing digital personal data'],
    proposed_date: null,
    enacted_date: '2023-08-11',
    effective_date: null,
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Rules published in draft January 2025; full commencement pending rule notification',
    key_provisions: [
      'Consent-based processing with notice requirements',
      'Data Principal (subject) rights: access, correction, erasure, grievance redressal',
      'Significant Data Fiduciary obligations',
      'Children\'s data (under 18): parental consent required',
      'Cross-border transfer: permitted to all countries except those notified as restricted',
    ],
    penalties: 'Up to INR 250 crore (~USD 30m) per violation.',
    extraterritorial_scope: 'Applies to processing outside India that is in connection with offering goods/services to data principals in India.',
    official_url: 'https://www.meity.gov.in/writereaddata/files/Digital%20Personal%20Data%20Protection%20Act%202023.pdf',
    source_url: 'https://www.meity.gov.in/data-protection-framework',
    summary: 'India\'s landmark data protection law. Enacted August 2023; draft rules published January 2025; full effect awaits rule notification. Shapes how AI systems can use Indian personal data for training and inference.',
    curriculum_relevance: 'Essential for any Indian AI curriculum, and important context for the ANI v. OpenAI jurisdictional debate.',
    tags: ['india', 'privacy', 'enacted-pending-commencement'],
  },

  // ── Japan ───────────────────────────────────────────────────────────────────
  {
    regulation_name: 'Copyright Act of Japan, Article 30-4 — Use of Works for Information Analysis',
    short_name: 'Japan Copyright Act Art. 30-4',
    jurisdiction: 'Japan',
    regulator: 'Agency for Cultural Affairs; courts',
    status: 'in_force',
    regulation_type: 'statute',
    scope: ['text and data mining', 'AI training on copyrighted works'],
    affected_sectors: ['AI developers training on Japanese copyrighted works'],
    proposed_date: null,
    enacted_date: '2018-05-25',
    effective_date: '2019-01-01',
    enforcement_date: '2019-01-01',
    next_milestone: null,
    next_milestone_notes: 'Agency for Cultural Affairs issued AI & Copyright guidelines March 2024 clarifying limits; being tested in Yomiuri / Nikkei / Asahi v. Perplexity',
    key_provisions: [
      'Permits the use of copyrighted works for information analysis (including AI training) without authorisation',
      'Exception does not apply where the use "unreasonably prejudices the interests of the copyright owner"',
      'Scope of "unreasonable prejudice" clarified in March 2024 guidelines',
    ],
    penalties: 'None under Art. 30-4 itself; ordinary copyright remedies apply if the exception is not available.',
    extraterritorial_scope: 'Territorially limited to acts of reproduction occurring in Japan.',
    official_url: 'https://www.japaneselawtranslation.go.jp/en/laws/view/4207',
    source_url: 'https://www.lexology.com/library/detail.aspx?g=a10ec535-678f-46ca-abe7-c2d61f1b348d',
    summary: 'Japan\'s deliberately permissive TDM/AI-training copyright exception. Article 30-4 has made Japan the most AI-training-friendly major jurisdiction. The Perplexity lawsuits filed August 2025 will test the limits of the "unreasonable prejudice" carve-out.',
    curriculum_relevance: 'The key permissive comparator to the EU AI Act\'s copyright transparency regime. Essential for understanding the global spread in AI training law.',
    tags: ['japan', 'copyright', 'tdm-exception', 'permissive'],
  },

  // ── South Korea ─────────────────────────────────────────────────────────────
  {
    regulation_name: 'Framework Act on the Development of Artificial Intelligence and Establishment of Trust (AI Basic Act)',
    short_name: 'Korea AI Framework Act',
    jurisdiction: 'South Korea',
    regulator: 'Ministry of Science and ICT (MSIT)',
    status: 'enacted',
    regulation_type: 'statute',
    scope: ['AI development and deployment', 'high-impact AI', 'generative AI'],
    affected_sectors: ['all sectors deploying AI in Korea'],
    proposed_date: null,
    enacted_date: '2024-12-26',
    effective_date: '2026-01-22',
    enforcement_date: '2026-01-22',
    next_milestone: '2026-01-22',
    next_milestone_notes: 'Promulgated 21 Jan 2025; one-year preparation period; subordinate regulations being finalised',
    key_provisions: [
      'Obligations for "high-impact" AI in healthcare, energy, public services etc.',
      'Mandatory labelling for certain GenAI applications',
      'Domestic representative requirement for foreign providers',
      'Cessation and correction order powers for MSIT',
      'Consolidates 19 prior AI bills into a single framework',
    ],
    penalties: 'Administrative fines up to KRW 30 million for specified violations.',
    extraterritorial_scope: 'Foreign providers must appoint a domestic representative for services provided in Korea.',
    official_url: 'https://www.msit.go.kr/eng/bbs/view.do?sCode=eng&mId=4&mPid=2&bbsSeqNo=42&nttSeqNo=1071',
    source_url: 'https://iapp.org/news/a/analyzing-south-korea-s-framework-act-on-the-development-of-ai',
    summary: 'South Korea\'s horizontal AI statute, passed 26 December 2024 with bipartisan support despite the political turmoil around President Yoon\'s martial-law declaration. Effective 22 January 2026.',
    curriculum_relevance: 'Asia-Pacific\'s first major horizontal AI statute. Important comparator to the EU AI Act and Chinese approach.',
    tags: ['south-korea', 'horizontal', 'high-impact'],
  },

  // ── International ───────────────────────────────────────────────────────────
  {
    regulation_name: 'Council of Europe Framework Convention on Artificial Intelligence and Human Rights, Democracy and the Rule of Law',
    short_name: 'CoE AI Framework Convention',
    jurisdiction: 'International',
    regulator: 'Conference of the Parties (to be constituted)',
    status: 'enacted',
    regulation_type: 'directive',
    scope: ['AI systems throughout their lifecycle', 'human rights, democracy, rule of law'],
    affected_sectors: ['public sector by default; private sector at each party\'s discretion'],
    proposed_date: null,
    enacted_date: '2024-09-05',
    effective_date: null,
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Enters into force on the first day of the month following a three-month period after 5 ratifications (incl. 3 CoE member states)',
    key_provisions: [
      'Protect human rights of persons affected by AI systems',
      'Safeguards for democratic processes and the rule of law',
      'Risk and impact management requirements',
      'Remedies and procedural rights for affected persons',
    ],
    penalties: 'Enforcement via national implementation by parties.',
    extraterritorial_scope: 'Treaty binds each party to regulate AI activities within its jurisdiction in line with the Convention.',
    official_url: 'https://www.coe.int/en/web/artificial-intelligence/the-framework-convention-on-artificial-intelligence',
    source_url: 'https://www.coe.int/en/web/portal/-/council-of-europe-opens-first-ever-global-treaty-on-ai-for-signature',
    summary: 'The first binding international AI treaty. Opened for signature 5 September 2024; signed that day by the EU and 10 states including the UK, US and Israel. Enters into force three months after five ratifications including three CoE members.',
    curriculum_relevance: 'The first international AI treaty — sets a potential global floor for AI human-rights protections. Watch the ratification count.',
    tags: ['international', 'treaty', 'human-rights'],
  },

  {
    regulation_name: 'Hiroshima Process International Code of Conduct for Organisations Developing Advanced AI Systems',
    short_name: 'G7 Hiroshima AI Code',
    jurisdiction: 'International',
    regulator: 'G7; OECD (reporting framework)',
    status: 'in_force',
    regulation_type: 'voluntary_code',
    scope: ['advanced AI systems, including foundation and generative models'],
    affected_sectors: ['developers of advanced AI systems voluntarily adhering'],
    proposed_date: null,
    enacted_date: '2023-10-30',
    effective_date: '2023-10-30',
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'OECD monitoring reports ongoing; code is referenced by EU AI Act Code of Practice and other initiatives',
    key_provisions: [
      'Identify, evaluate and mitigate risks across the AI lifecycle',
      'Post-deployment monitoring and incident reporting',
      'Public transparency on capabilities and limitations',
      'Information sharing with governments, civil society and academia',
      'Invest in security controls and content authentication',
    ],
    penalties: 'Voluntary — no direct penalties.',
    extraterritorial_scope: 'Voluntary adherence by signatories; referenced globally.',
    official_url: 'https://www.mofa.go.jp/files/100573471.pdf',
    source_url: 'https://oecd.ai/en/wonk/hiroshima-process-international-code-of-conduct',
    summary: 'The G7 Hiroshima Process international code of conduct for advanced AI developers, agreed in October 2023 alongside the Bletchley Declaration and used as one of the reference points for voluntary frontier-AI commitments globally.',
    curriculum_relevance: 'Key voluntary international framework — students should understand how it interlocks with the EU AI Act GPAI Code of Practice and national voluntary commitments.',
    tags: ['international', 'g7', 'voluntary', 'frontier-models'],
  },

  {
    regulation_name: 'UNESCO Recommendation on the Ethics of Artificial Intelligence',
    short_name: 'UNESCO AI Ethics Recommendation',
    jurisdiction: 'International',
    regulator: 'UNESCO (monitoring); member states (national implementation)',
    status: 'in_force',
    regulation_type: 'voluntary_code',
    scope: ['all AI systems', 'ethical values and principles'],
    affected_sectors: ['public policy and procurement; informs national frameworks worldwide'],
    proposed_date: null,
    enacted_date: '2021-11-23',
    effective_date: '2021-11-23',
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Implementation monitored via Readiness Assessment Methodology (RAM) in member states',
    key_provisions: [
      'Values: respect for human rights, environment, diversity, peace',
      'Principles: proportionality, safety, fairness, privacy, transparency, human oversight, accountability',
      'Policy actions across data governance, gender, culture, education and research',
      'Readiness Assessment Methodology for member states',
    ],
    penalties: 'Voluntary — not legally binding.',
    extraterritorial_scope: 'Global voluntary instrument; adopted by 194 UNESCO member states.',
    official_url: 'https://www.unesco.org/en/articles/recommendation-ethics-artificial-intelligence',
    source_url: 'https://www.unesco.org/en/artificial-intelligence/recommendation-ethics',
    summary: 'Adopted unanimously by UNESCO\'s 194 member states in November 2021. The first global ethical framework for AI adopted by a UN body; heavily referenced in national AI strategies worldwide including Africa and Latin America.',
    curriculum_relevance: 'The single most globally-representative AI ethics instrument. Useful to ground curriculum discussion beyond US/EU/China.',
    tags: ['international', 'un', 'ethics', 'voluntary'],
  },

  {
    regulation_name: 'The Bletchley Declaration by Countries Attending the AI Safety Summit',
    short_name: 'Bletchley Declaration',
    jurisdiction: 'International',
    regulator: 'Signatory states and the AI Safety Institutes network',
    status: 'in_force',
    regulation_type: 'voluntary_code',
    scope: ['frontier AI safety', 'international cooperation'],
    affected_sectors: ['governments and AI safety institutes'],
    proposed_date: null,
    enacted_date: '2023-11-01',
    effective_date: '2023-11-01',
    enforcement_date: null,
    next_milestone: null,
    next_milestone_notes: 'Seoul Declaration (May 2024) and Paris AI Action Summit (Feb 2025) are successor instruments',
    key_provisions: [
      'Recognition of frontier-AI risks including misuse, loss of control and systemic harms',
      'Agreement to international cooperation on safety research and evaluation',
      'Foundation for the network of national AI Safety Institutes',
    ],
    penalties: 'Voluntary — no direct penalties.',
    extraterritorial_scope: 'Political declaration signed by 28 countries + EU including the US, UK, China, India, and EU member states.',
    official_url: 'https://www.gov.uk/government/publications/ai-safety-summit-2023-the-bletchley-declaration',
    source_url: 'https://www.gov.uk/government/publications/ai-safety-summit-2023-the-bletchley-declaration',
    summary: 'The 28-country + EU political declaration from the UK\'s AI Safety Summit at Bletchley Park on 1 November 2023. Catalysed the network of AI Safety Institutes (UK, US, EU, Japan, Singapore, Korea, India, Kenya) and subsequent AI safety summits in Seoul and Paris.',
    curriculum_relevance: 'Origin-point for the modern AI-safety diplomatic architecture. Essential historical anchor.',
    tags: ['international', 'ai-safety', 'diplomacy', 'frontier'],
  },
];

function coalesce(v) { return v === undefined ? null : v; }

async function run() {
  const client = await pool.connect();
  let inserted = 0;
  let skipped = 0;
  try {
    for (const r of REGS) {
      const sourceUrls = [r.source_url, r.official_url].filter(Boolean);
      const tags = Array.from(new Set([
        'ai-regulation',
        r.regulation_type,
        r.jurisdiction.toLowerCase().replace(/\s+/g, '-'),
        ...(r.tags || []),
      ].filter(Boolean))).slice(0, 15);

      const res = await client.query(
        `INSERT INTO ai_regulations
           (regulation_name, short_name, jurisdiction, regulator, status, regulation_type,
            scope, affected_sectors,
            proposed_date, enacted_date, effective_date, enforcement_date,
            next_milestone, next_milestone_notes,
            key_provisions, penalties, extraterritorial_scope,
            official_url, source_url, source_urls,
            summary, curriculum_relevance, is_curriculum_relevant, tags)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24)
         ON CONFLICT (short_name, jurisdiction) DO NOTHING
         RETURNING id`,
        [
          r.regulation_name,
          coalesce(r.short_name),
          r.jurisdiction,
          coalesce(r.regulator),
          r.status || 'in_force',
          coalesce(r.regulation_type),
          r.scope || [],
          r.affected_sectors || [],
          coalesce(r.proposed_date),
          coalesce(r.enacted_date),
          coalesce(r.effective_date),
          coalesce(r.enforcement_date),
          coalesce(r.next_milestone),
          coalesce(r.next_milestone_notes),
          r.key_provisions || [],
          coalesce(r.penalties),
          coalesce(r.extraterritorial_scope),
          coalesce(r.official_url),
          coalesce(r.source_url),
          sourceUrls,
          coalesce(r.summary),
          coalesce(r.curriculum_relevance),
          true,
          tags,
        ]
      );
      if (res.rowCount > 0) {
        inserted += 1;
        console.log(`  inserted: ${r.short_name || r.regulation_name} (${r.jurisdiction})`);
      } else {
        skipped += 1;
        console.log(`  skipped (already exists): ${r.short_name || r.regulation_name}`);
      }
    }
    console.log(`\nDone. Inserted ${inserted}, skipped ${skipped}, total input ${REGS.length}.`);
  } finally {
    client.release();
    await pool.end();
  }
}

run().catch(err => { console.error(err); process.exit(1); });
