CREATE TABLE IF NOT EXISTS ai_lawsuits (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  case_name VARCHAR(500) NOT NULL,
  plaintiffs TEXT[] DEFAULT '{}',
  defendants TEXT[] DEFAULT '{}',
  court VARCHAR(300),
  judge VARCHAR(200),
  jurisdiction VARCHAR(100),   -- 'US Federal', 'US State', 'EU', 'UK', 'International'
  district VARCHAR(200),       -- 'N.D. Cal.', 'S.D.N.Y.', 'C.D. Cal.' etc.
  circuit VARCHAR(100),        -- '9th Circuit', '3rd Circuit' etc.
  status VARCHAR(50) DEFAULT 'active',  -- 'active', 'settled', 'dismissed', 'appealing', 'decided'
  case_type VARCHAR(100) DEFAULT 'copyright', -- 'copyright', 'privacy', 'defamation', 'labour', 'contract', 'other'
  key_issues TEXT[] DEFAULT '{}',
  filing_date DATE,
  last_update DATE,
  next_deadline DATE,
  next_deadline_notes TEXT,
  outcome TEXT,
  settlement_amount VARCHAR(200),
  case_url TEXT,
  source_url TEXT,
  summary TEXT,
  curriculum_relevance TEXT,
  is_curriculum_relevant BOOLEAN DEFAULT true,
  tags TEXT[] DEFAULT '{}',
  external_id VARCHAR(200),    -- CourtListener ID or other external reference
  last_scraped_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ai_lawsuits_status ON ai_lawsuits(status);
CREATE INDEX IF NOT EXISTS idx_ai_lawsuits_defendants ON ai_lawsuits USING gin(defendants);
CREATE INDEX IF NOT EXISTS idx_ai_lawsuits_updated ON ai_lawsuits(updated_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_lawsuits_case_name ON ai_lawsuits(case_name);

-- Seed data: 42 cases from Oct 2025 tracker (chatgptiseatingtheworld.com)
INSERT INTO ai_lawsuits (case_name, plaintiffs, defendants, court, judge, jurisdiction, district, circuit, status, case_type, key_issues, filing_date, last_update, next_deadline, next_deadline_notes, outcome, settlement_amount, source_url, summary, curriculum_relevance) VALUES

-- APPEALS COURTS
('Doe 1 v. GitHub', ARRAY['Doe 1 (anonymous developers)'], ARRAY['GitHub', 'Microsoft', 'OpenAI'], 'US Court of Appeals', NULL, 'US Federal', NULL, '9th Circuit', 'appealing', 'copyright', ARRAY['DMCA anti-circumvention', 'open source licence violations', 'Copilot training data'], '2022-11-03', '2025-10-08', NULL, 'Fully briefed, awaiting oral argument', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Developers allege GitHub Copilot violates DMCA and open source licences by reproducing code without attribution. Fully briefed in the 9th Circuit, awaiting oral argument.', 'Direct case study for Legal sector training: DMCA scope, open source licencing, and developer rights in the AI era.'),

('Thomson Reuters v. ROSS Intelligence', ARRAY['Thomson Reuters'], ARRAY['ROSS Intelligence'], 'US Court of Appeals', NULL, 'US Federal', NULL, '3rd Circuit', 'appealing', 'copyright', ARRAY['fair use in AI training', 'legal database copyright', 'headnotes copyrightability'], '2020-05-06', '2025-10-08', NULL, 'ROSS opening brief filed; 10 amici supporting', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Thomson Reuters sued ROSS for using Westlaw headnotes to train a competing AI legal research tool. District court ruled for Reuters on fair use. ROSS appealing in 3rd Circuit with 10 amici supporting.', 'Landmark case for Legal sector: first major AI training fair use ruling, directly impacts how AI legal tools are built and what legal professionals can use.'),

('Raw Story Media v. OpenAI', ARRAY['Raw Story Media', 'AlterNet Media'], ARRAY['OpenAI'], 'US Court of Appeals', NULL, 'US Federal', NULL, '2nd Circuit', 'appealing', 'copyright', ARRAY['DMCA CMI removal', 'Article III standing', 'news publisher rights'], '2024-02-28', '2025-10-08', '2025-11-10', 'OpenAI appellate brief due Nov 10 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'News publishers allege OpenAI stripped copyright management information from their articles. District court dismissed for lack of standing. Publishers appealing in 2nd Circuit.', 'Key case for Media sector: tests whether removing CMI from news content during AI training violates the DMCA. Critical for journalists understanding AI and their content rights.'),

-- SETTLED
('Bartz v. Anthropic', ARRAY['Andrea Bartz', 'Charles Graeber', 'Kirk Wallace Johnson'], ARRAY['Anthropic'], 'US District Court', 'William Alsup', 'US Federal', 'N.D. Cal.', NULL, 'settled', 'copyright', ARRAY['fiction training data', 'class action', 'author rights'], '2023-08-21', '2025-07-17', NULL, 'Preliminary settlement approval granted 17 Jul 2025', 'Class action settlement', '$1,500,000', 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Authors sued Anthropic for training Claude on their books without permission. Settled for $1.5M class action fund. Preliminary approval granted July 2025.', 'First significant AI training settlement. Useful benchmark for Legal sector on how AI companies are resolving copyright claims and what damages look like.'),

('Vacker v. Eleven Labs', ARRAY['Vacker (voice actors)'], ARRAY['Eleven Labs'], 'US District Court', NULL, 'US Federal', 'D. Delaware', NULL, 'settled', 'copyright', ARRAY['voice cloning', 'performer rights', 'audio training data'], NULL, '2025-10-08', NULL, 'Settled on confidential terms', 'Confidential settlement', 'Confidential', 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Voice actors sued Eleven Labs over AI voice cloning without consent. Settled on confidential terms.', 'Important for Media sector training on AI voice cloning, performer rights, and the emerging legal landscape for synthetic audio.'),

-- N.D. CAL — SUMMARY JUDGMENT TRACK
('Kadrey v. Meta', ARRAY['Richard Kadrey', 'Sarah Silverman', 'Christopher Golden', 'Ta-Nehisi Coates', 'Junot Díaz'], ARRAY['Meta'], 'US District Court', 'Vince Chhabria', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['LLaMA training data', 'fair use', 'DMCA CMI', 'shadow library'], '2023-07-07', '2025-06-27', '2026-04-02', 'Summary judgment hearing 2 Apr 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Authors sued Meta for training LLaMA on books from shadow libraries. Judge Chhabria granted partial summary judgment to Meta on DMCA CMI claim June 2025. Fair use to be decided April 2026.', 'Closely watched case — Judge Chhabria''s fair use ruling in 2026 will be a landmark for how AI training interacts with copyright. Essential case study for Legal cohorts.'),

('Andersen v. Stability AI', ARRAY['Sarah Andersen', 'Kelly McKernan', 'Karla Ortiz'], ARRAY['Stability AI', 'Midjourney', 'DeviantArt'], 'US District Court', 'William Orrick', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['image training data', 'visual artists rights', 'diffusion model copyright', 'style copying'], '2023-01-13', '2025-10-08', '2026-11-04', 'Summary judgment hearing 4 Nov 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Visual artists sued image AI companies for training on their artwork. Second amended complaint filed Oct 2024. Summary judgment set for Nov 2026.', 'Pioneer AI art copyright case. Critical for Media sector training on AI-generated imagery, visual rights, and what constitutes infringement in generative models.'),

('In re Google Generative AI', ARRAY['Jingna Zhang', 'Leovy (consolidated)'], ARRAY['Google'], 'US District Court', 'Susan van Keulen', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['Gemini training data', 'image copyright', 'fair use'], '2024-01-01', '2025-09-25', '2026-05-06', 'Summary judgment hearing deadline 6 May 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Consolidated class action against Google for training Gemini on copyrighted images. Second amended complaint filed September 2025.', 'Tests fair use in image AI training at Google scale. Important context for Media sector training on AI and visual content rights.'),

('Concord Music v. Anthropic', ARRAY['Concord Music', 'Universal Music', 'ABKCO'], ARRAY['Anthropic'], 'US District Court', 'Susan van Keulen', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['song lyrics copyright', 'music training data', 'Claude outputs'], '2023-10-18', '2025-10-08', '2026-06-10', 'Summary judgment hearing 10 Jun 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Major music publishers sued Anthropic for Claude reproducing song lyrics. Motion to dismiss denied Oct 2025. Summary judgment June 2026.', 'Tests whether AI output reproducing song lyrics is infringement. Relevant to Media sector training on AI-generated creative content and copyright risk.'),

('Nazemian v. NVIDIA', ARRAY['Farnaz Nazemian', 'Dubus (consolidated)'], ARRAY['NVIDIA'], 'US District Court', 'Jon Tigar', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['NeMo LLM training data', 'book copyright', 'class certification'], NULL, '2025-10-08', '2026-07-31', 'Class cert motion due 31 Jul 2026; SJ motion due 21 Aug 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Authors sued NVIDIA for training NeMo language models on their books. Consolidated class action. Discovery ongoing with class certification due mid-2026.', 'Extends copyright AI litigation to hardware/infrastructure companies. Useful for Legal sector on the full supply chain of AI liability.'),

('In re Mosaic LLM (O''Nan v. Databricks)', ARRAY['Stewart O''Nan', 'Viet Thanh Nguyen', 'Makkai'], ARRAY['Databricks', 'Mosaic ML'], 'US District Court', 'Charles Breyer', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['DBRX training data', 'book copyright', 'enterprise AI'], NULL, '2025-09-02', '2026-07-10', 'Summary judgment replies due 10 Jul 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Authors sued Databricks for training enterprise AI model DBRX on copyrighted books. First amended complaint answered September 2025.', 'Extends copyright litigation to enterprise AI vendors. Important for Legal sector on corporate AI procurement and training data liability.'),

-- N.D. CAL — DISCOVERY PHASE
('Getty Images v. Stability AI (California)', ARRAY['Getty Images'], ARRAY['Stability AI'], 'US District Court', 'Jeffrey White', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['stock image training data', 'watermark removal', 'commercial image rights', 'DMCA'], '2023-02-03', '2025-08-14', NULL, 'Complaint filed 14 Aug 2025 (California action)', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Getty Images sued Stability AI for training Stable Diffusion on millions of watermarked stock photos. California action filed August 2025 alongside Delaware case.', 'Landmark stock photography case — directly relevant to Media sector on AI and visual content rights, and the commercial implications of training data sources.'),

('Hendrix v. Apple', ARRAY['Jimi Hendrix Estate'], ARRAY['Apple'], 'US District Court', 'Yvonne Gonzalez Rogers', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['AI music generation', 'estate rights', 'sound recording copyright'], NULL, '2025-10-08', '2025-12-15', 'Case management conference 15 Dec 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Jimi Hendrix estate sued Apple over AI music generation. Case management conference December 2025.', 'Tests posthumous rights in the AI era. Relevant to Media sector training on AI audio and music generation.'),

('Martinez-Conde v. Apple', ARRAY['Susana Martinez-Conde'], ARRAY['Apple'], 'US District Court', 'Virginia Labson Freeman', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['scientific content training data', 'academic copyright'], NULL, '2025-10-08', '2026-01-22', 'Case management conference 22 Jan 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Neuroscientist sued Apple for training AI on scientific content. Case management conference January 2026.', 'Extends AI copyright litigation to academic and scientific publishing. Useful context for Legal sector training.'),

('Strike 3 Holdings v. Meta', ARRAY['Strike 3 Holdings'], ARRAY['Meta'], 'US District Court', 'Susan van Keulen', 'US Federal', 'N.D. Cal.', NULL, 'active', 'copyright', ARRAY['adult content training data', 'DMCA', 'LLaMA'], NULL, '2025-10-08', '2026-01-21', 'Case management conference 21 Jan 2026', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Adult content company sued Meta for training LLaMA on its copyrighted material. Early discovery stage.', 'Tests the full breadth of training data copyright claims including adult content. Useful for Legal sector training on AI copyright scope.'),

-- N.D. CAL — DISMISSED
('Millette v. Google', ARRAY['Millette'], ARRAY['Google'], 'US District Court', NULL, 'US Federal', 'N.D. Cal.', NULL, 'dismissed', 'copyright', ARRAY['Bard training data'], NULL, '2025-10-08', NULL, 'Voluntarily dismissed', 'Voluntarily dismissed', NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Voluntarily dismissed by plaintiff.', NULL),

('Millette v. NVIDIA', ARRAY['Millette'], ARRAY['NVIDIA'], 'US District Court', NULL, 'US Federal', 'N.D. Cal.', NULL, 'dismissed', 'copyright', ARRAY['NeMo training data'], NULL, '2025-10-08', NULL, 'Voluntarily dismissed', 'Voluntarily dismissed', NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Voluntarily dismissed by plaintiff.', NULL),

('Brave Software v. News Corp.', ARRAY['Brave Software'], ARRAY['News Corp.'], 'US District Court', NULL, 'US Federal', 'N.D. Cal.', NULL, 'dismissed', 'other', ARRAY['AI search', 'news aggregation'], NULL, '2025-10-08', NULL, 'Voluntarily dismissed', 'Voluntarily dismissed', NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Voluntarily dismissed by plaintiff.', NULL),

-- C.D. CAL
('Alcon Entertainment v. Tesla', ARRAY['Alcon Entertainment'], ARRAY['Tesla'], 'US District Court', 'George Wu', 'US Federal', 'C.D. Cal.', NULL, 'active', 'copyright', ARRAY['Blade Runner 2049 imagery', 'AI training data', 'film copyright', 'Optimus robot'], '2024-08-06', '2025-10-02', NULL, 'Third amended complaint filed 2 Oct 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Film studio alleged Tesla used Blade Runner 2049 imagery to train its Optimus robot AI without permission. On third amended complaint as of October 2025.', 'Unusual case extending AI copyright to robotics training. Interesting for Legal and Media sectors on the range of AI use cases being litigated.'),

('Disney v. Midjourney', ARRAY['Disney'], ARRAY['Midjourney'], 'US District Court', 'John Kronstadt', 'US Federal', 'C.D. Cal.', NULL, 'active', 'copyright', ARRAY['Disney character image rights', 'AI image generation', 'DMCA'], '2024-06-07', '2025-08-06', NULL, 'Answer filed 6 Aug 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Disney sued Midjourney for generating images of its characters. Midjourney filed its answer August 2025.', 'High-profile brand protection case. Directly relevant to Media sector training on AI image generation and IP risk management.'),

('Warner Bros. v. Midjourney', ARRAY['Warner Bros. Discovery'], ARRAY['Midjourney'], 'US District Court', 'John Kronstadt', 'US Federal', 'C.D. Cal.', NULL, 'active', 'copyright', ARRAY['DC Comics characters', 'Harry Potter imagery', 'AI image generation'], '2025-09-04', '2025-09-04', NULL, 'Complaint filed Sep 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Warner Bros. filed suit against Midjourney for generating images of DC and Harry Potter characters. Filed September 2025, very early stage.', 'Follows the Disney pattern — major studios asserting IP rights against AI image generators. Useful for Media sector training.'),

('Disney v. Minimax', ARRAY['Disney'], ARRAY['Minimax (Chinese AI company)'], 'US District Court', 'Fernando Aenlle-Rocha', 'US Federal', 'C.D. Cal.', NULL, 'active', 'copyright', ARRAY['AI video generation', 'Disney character copyright', 'cross-border AI IP'], '2025-09-16', '2025-09-16', NULL, 'Complaint filed 16 Sep 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Disney sued Chinese AI video generator Minimax for producing videos featuring its characters. First major action against a Chinese AI company by a US studio.', 'Important cross-border AI IP case. Relevant for Legal sector training on global AI regulation and enforcement challenges.'),

-- MDL — SDNY — CLASS ACTION
('In re OpenAI Copyright Infringement (MDL)', ARRAY['Multiple authors and publishers'], ARRAY['OpenAI', 'Microsoft'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['GPT training data', 'class action', 'author rights', 'fair use'], '2024-06-13', '2025-10-08', NULL, 'Motion to dismiss hearing 8 Oct 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Consolidated MDL class action against OpenAI for training GPT models on copyrighted works. Motion to dismiss heard October 2025.', 'The central copyright AI litigation of the era. Essential case study for both Legal and Media sectors on AI training data rights.'),

('Authors Guild v. OpenAI', ARRAY['Authors Guild', 'John Grisham', 'Jodi Picoult', 'George R.R. Martin'], ARRAY['OpenAI', 'Microsoft'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['GPT training data', 'author rights', 'book copyright'], '2023-09-20', '2025-10-08', NULL, 'Discovery ongoing; consolidated in MDL', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Authors Guild and prominent authors sued OpenAI for training ChatGPT on their books. Consolidated into the MDL. Discovery ongoing.', 'High-profile case with household names. Excellent for Media sector training on illustrating AI copyright stakes to non-legal audiences.'),

('Tremblay v. OpenAI', ARRAY['Paul Tremblay', 'Mona Awad'], ARRAY['OpenAI'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['GPT training data', 'book copyright'], '2023-06-28', '2024-03-13', NULL, 'Consolidated in MDL; first amended complaint 13 Mar 2024', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'One of the first author lawsuits against OpenAI. Now consolidated in the MDL.', 'Pioneer case in author-vs-AI-company litigation. Useful historical context for Legal sector training.'),

('Silverman v. OpenAI', ARRAY['Sarah Silverman', 'Richard Kadrey', 'Christopher Golden'], ARRAY['OpenAI'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['GPT training data', 'book copyright'], '2023-07-07', '2024-03-13', NULL, 'Consolidated in MDL; first amended complaint 13 Mar 2024', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Sarah Silverman and authors sued OpenAI. High-profile case now consolidated in the MDL.', 'Public-facing case useful for illustrating AI copyright issues. Good for Media sector training with celebrity plaintiff angle.'),

('New York Times v. Microsoft and OpenAI', ARRAY['New York Times'], ARRAY['Microsoft', 'OpenAI'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['news content training data', 'verbatim reproduction', 'publisher rights', 'RAG retrieval'], '2023-12-27', '2025-05-28', NULL, 'Second amended complaint 28 May 2025; discovery ongoing', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'New York Times sued Microsoft and OpenAI for training on and retrieving news content. The most significant news publisher case. Discovery ongoing with second amended complaint May 2025.', 'The defining news publisher AI case. Essential for Media sector training — directly addresses the relationship between AI companies and journalism, and what content rights mean in practice.'),

('Daily News v. Microsoft', ARRAY['New York Daily News', 'Chicago Tribune', 'Orlando Sentinel', 'others'], ARRAY['Microsoft', 'OpenAI'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['news content training data', 'publisher consortium', 'Bing AI'], '2024-04-30', '2025-10-08', NULL, 'Consolidated in MDL', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Coalition of regional US newspapers sued Microsoft and OpenAI for using their content to train AI. Consolidated in the MDL.', 'Demonstrates the breadth of news publisher opposition to AI training. Useful for Media sector training on collective action and industry responses to AI.'),

('Center for Investigative Reporting v. OpenAI', ARRAY['Center for Investigative Reporting', 'Mother Jones'], ARRAY['OpenAI', 'Microsoft'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['investigative journalism copyright', 'nonprofit news rights'], '2024-06-27', '2024-09-24', NULL, 'First amended complaint 24 Sep 2024; consolidated in MDL', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Investigative journalism nonprofit sued OpenAI for training on its content. Consolidated in the MDL.', 'Directly relevant to Media sector training — nonprofit investigative journalism rights in the AI era.'),

('Intercept Media v. OpenAI', ARRAY['The Intercept'], ARRAY['OpenAI', 'Microsoft'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['investigative news content', 'DMCA CMI removal'], '2024-02-28', '2024-12-05', NULL, 'Amended answer filed 5 Dec 2024; consolidated in MDL', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'The Intercept sued OpenAI and Microsoft for stripping CMI from its content during AI training. Consolidated in MDL.', 'DMCA CMI angle is directly relevant to Media sector — how AI training erases attribution metadata from news content.'),

('Ziff Davis v. OpenAI', ARRAY['Ziff Davis', 'PCMag', 'Mashable', 'IGN'], ARRAY['OpenAI'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['tech media copyright', 'publisher rights', 'GPT training'], '2024-04-17', '2025-07-07', NULL, 'First amended complaint 7 Jul 2025; consolidated in MDL', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Major tech media publisher Ziff Davis sued OpenAI for training on its content including PCMag, Mashable, and IGN. First amended complaint July 2025.', 'Tech media publisher rights case. Useful for Media sector on the range of publishers asserting AI copyright claims.'),

-- SDNY — NON-MDL
('Dow Jones v. Perplexity AI', ARRAY['Dow Jones', 'New York Post'], ARRAY['Perplexity AI'], 'US District Court', 'Colleen McMahon', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['AI search summarisation', 'news aggregation', 'hot news doctrine', 'Perplexity'], '2024-10-21', '2025-10-06', NULL, 'Answer filed 6 Oct 2025; second amended complaint 28 Jan 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Dow Jones and New York Post sued Perplexity AI for summarising and reproducing their news content in search results. Tests whether AI search engines can summarise paywalled content.', 'Critical case for Media sector — directly tests whether AI summarisation of news is copyright infringement. Central to teaching AI and journalism ethics.'),

('Encyclopaedia Britannica v. Perplexity AI', ARRAY['Encyclopaedia Britannica'], ARRAY['Perplexity AI'], 'US District Court', 'Jennifer Rochon', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['AI search summarisation', 'encyclopedia content', 'knowledge aggregation'], NULL, '2025-10-08', '2025-11-03', 'Answer due 3 Nov 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Encyclopaedia Britannica sued Perplexity AI for reproducing its content in AI search answers.', 'Part of the Perplexity AI cluster of cases testing AI search and knowledge aggregation copyright.'),

('UMG Recordings v. Udio', ARRAY['Universal Music Group', 'Sony Music', 'Warner Music Group'], ARRAY['Udio'], 'US District Court', 'Alvin Hellerstein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['AI music generation', 'sound recording copyright', 'training data'], '2024-06-24', '2025-10-06', NULL, 'First amended complaint 6 Oct 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Major labels sued AI music generator Udio for training on copyrighted recordings. First amended complaint October 2025. Sister case to Sony v. Suno.', 'Central AI music copyright case. Directly relevant to Media sector training on AI audio generation and music industry rights.'),

('Justice v. Udio', ARRAY['Ashley Justice (musicians collective)'], ARRAY['Udio'], 'US District Court', 'Alvin Hellerstein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['AI music generation', 'independent musician rights', 'sound recording'], NULL, '2025-09-17', NULL, 'Answer filed 17 Sep 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Independent musicians sued Udio alongside the major label action. Raises independent artist rights in AI music generation.', 'Complements the major label cases — gives independent musician perspective on AI music rights.'),

('Advance Local Media v. Cohere', ARRAY['Advance Local Media', 'MLive', 'NJ.com', 'oregonlive'], ARRAY['Cohere'], 'US District Court', 'Colleen McMahon', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['enterprise AI training', 'local news copyright', 'Cohere LLM'], '2024-12-11', '2025-07-02', NULL, 'Motion to dismiss filed May 2025; opposition filed Jul 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Regional news publishers sued enterprise AI company Cohere for training on their content. Extends AI copyright litigation to B2B LLM providers.', 'Important for Legal sector — enterprise AI vendor liability for training data. Different profile from consumer AI cases.'),

('Lehrman v. Lovo', ARRAY['Bev Standing', 'Lehrman'], ARRAY['Lovo'], 'US District Court', 'J. Paul Oetken', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['voice actor rights', 'voice cloning', 'performer rights', 'synthetic audio'], NULL, '2025-10-06', NULL, 'Opposition to motion to dismiss filed 6 Oct 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'Voice actors sued Lovo AI for cloning their voices without consent. Opposition to motion to dismiss filed October 2025.', 'Voice cloning rights case — highly relevant to Media sector training on AI audio, synthetic voice, and performer consent.'),

('Bird v. Microsoft', ARRAY['Bird'], ARRAY['Microsoft'], 'US District Court', 'Sidney Stein', 'US Federal', 'S.D.N.Y.', NULL, 'active', 'copyright', ARRAY['Copilot training data', 'code copyright'], '2025-06-25', '2025-06-25', NULL, 'Stayed pending MDL rulings; complaint filed Jun 2025', NULL, NULL, 'https://chatgptiseatingtheworld.com/2025/10/08/status-of-all-51-copyright-lawsuits-v-ai-oct-8-2025-no-more-decisions-on-fair-use-in-2025/', 'New action against Microsoft for Copilot training. Stayed pending MDL rulings from the consolidated cases.', NULL)

ON CONFLICT (case_name) DO NOTHING;
