// Renders two AI-generated insights for a case or regulation: industry impact
// + predicted outcome. Claims are linked to the exact cases/regulations the
// model cited so readers can verify each one.
//
// When `canEdit` is true (admin viewing), each insight gains an Edit button that
// reveals a textarea for correcting the content, plus the parent page exposes
// Regenerate / Build-Timeline actions.
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { formatDate } from './publicHelpers.jsx';
import { apiFetch } from '../../hooks/useApi.js';

const TYPE_META = {
  industry_impact:   { label: 'Industry impact',     color: '#6366F1', icon: '◇' },
  predicted_outcome: { label: 'Predicted outcome',   color: '#10B981', icon: '→' },
  precedent_analysis:{ label: 'Precedent analysis',  color: '#F59E0B', icon: '§' },
};

export default function InsightsBox({ insights, subjectKind, subjectId, canEdit = false, onChanged }) {
  if (!insights || insights.length === 0) {
    return (
      <div className="card" style={{ padding: 16, marginBottom: 16, background: '#F9FAFB', borderStyle: 'dashed' }}>
        <div style={{ fontSize: 12, color: 'var(--text-secondary)', lineHeight: 1.5 }}>
          <strong>No insights generated yet.</strong> {canEdit
            ? 'Click "Generate insights" above to build them.'
            : 'Industry impact + predicted outcome analysis can be generated by an admin via the Legal Sources dashboard.'}
        </div>
      </div>
    );
  }

  return (
    <section style={{ marginBottom: 16 }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 8 }}>
        Insights · AI-generated
      </div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(340px, 1fr))', gap: 12 }}>
        {insights.map(ins => (
          <InsightCard
            key={ins.insight_type}
            ins={ins}
            subjectKind={subjectKind}
            subjectId={subjectId}
            canEdit={canEdit}
            onChanged={onChanged}
          />
        ))}
      </div>
    </section>
  );
}

function InsightCard({ ins, subjectKind, subjectId, canEdit, onChanged }) {
  const meta = TYPE_META[ins.insight_type] || { label: ins.insight_type, color: '#6B7280', icon: '•' };
  const [editing, setEditing] = useState(false);
  const [draft, setDraft]     = useState(ins.content || '');
  const [saving, setSaving]   = useState(false);
  const [error, setError]     = useState(null);

  async function save() {
    if (!draft.trim()) return;
    setSaving(true); setError(null);
    try {
      await apiFetch(`/legal-sources/insights/${subjectKind}/${subjectId}/${ins.insight_type}`, {
        method: 'PUT',
        body: JSON.stringify({ content: draft.trim() }),
      });
      setEditing(false);
      onChanged?.();
    } catch (err) {
      setError(err.message || 'Save failed');
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="card" style={{ padding: 14, borderTop: `3px solid ${meta.color}` }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{
            width: 20, height: 20, borderRadius: '50%', background: meta.color, color: 'white',
            display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
            fontSize: 11, fontWeight: 700,
          }}>{meta.icon}</span>
          <span style={{ fontSize: 13, fontWeight: 700 }}>{meta.label}</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <span style={{ fontSize: 10, color: 'var(--text-secondary)' }}>
            {ins.confidence != null && <>conf {Number(ins.confidence).toFixed(2)} · </>}
            {formatDate(ins.generated_at)}
          </span>
          {canEdit && !editing && (
            <button
              type="button"
              onClick={() => { setDraft(ins.content || ''); setEditing(true); setError(null); }}
              style={adminBtnStyle}
            >Edit</button>
          )}
        </div>
      </div>

      {editing ? (
        <>
          <textarea
            value={draft}
            onChange={e => setDraft(e.target.value)}
            rows={Math.max(6, Math.min(20, (draft.match(/\n/g) || []).length + 4))}
            style={{
              width: '100%', fontSize: 13, lineHeight: 1.6,
              padding: 8, borderRadius: 4, border: '1px solid var(--border-color)',
              fontFamily: 'inherit', resize: 'vertical',
            }}
          />
          <div style={{ fontSize: 10, color: 'var(--text-secondary)', marginTop: 4 }}>
            Keep <code>[lawsuit:UUID]</code> / <code>[regulation:UUID]</code> markers intact so citation chips still render.
          </div>
          {error && <div style={{ fontSize: 11, color: '#991B1B', marginTop: 6 }}>{error}</div>}
          <div style={{ marginTop: 8, display: 'flex', gap: 6 }}>
            <button type="button" onClick={save} disabled={saving} style={{ ...adminBtnStyle, background: meta.color, color: 'white', borderColor: meta.color }}>
              {saving ? 'Saving…' : 'Save'}
            </button>
            <button type="button" onClick={() => setEditing(false)} disabled={saving} style={adminBtnStyle}>Cancel</button>
          </div>
        </>
      ) : (
        <div style={{ fontSize: 13, lineHeight: 1.65, color: 'var(--text-primary)', whiteSpace: 'pre-wrap' }}>
          {renderWithCitations(ins.content, ins.citations || [])}
        </div>
      )}

      {!editing && (ins.citations || []).length > 0 && (
        <div style={{ marginTop: 10, paddingTop: 10, borderTop: '1px solid #E5E7EB' }}>
          <div style={{ fontSize: 10, fontWeight: 700, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>
            Cites
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4 }}>
            {ins.citations.map((c, i) => (
              <Link key={`${c.kind}:${c.id}:${i}`}
                    to={c.kind === 'lawsuit' ? `/legal/lawsuits/${c.id}` : `/legal/regulations/${c.id}`}
                    style={{
                      fontSize: 11, padding: '2px 8px', borderRadius: 10,
                      background: c.kind === 'lawsuit' ? '#EEF2FF' : '#D1FAE5',
                      color: c.kind === 'lawsuit' ? '#4F46E5' : '#065F46',
                      textDecoration: 'none', fontWeight: 600,
                    }}>
                {c.kind === 'lawsuit' ? '⚖ ' : '📜 '}{c.name}
              </Link>
            ))}
          </div>
        </div>
      )}

      <div style={{ marginTop: 8, fontSize: 10, color: 'var(--text-secondary)', fontStyle: 'italic' }}>
        AI-generated · not legal advice
      </div>
    </div>
  );
}

const adminBtnStyle = {
  fontSize: 11, padding: '3px 10px', borderRadius: 4,
  border: '1px solid var(--border-color)', background: 'var(--card-bg)',
  color: 'var(--text-primary)', cursor: 'pointer', fontWeight: 600,
};

// Replace [lawsuit:UUID] and [regulation:UUID] markers inline with styled
// superscript chips that link to the corresponding detail page.
function renderWithCitations(text, citations) {
  if (!text) return null;
  const byId = new Map(citations.map(c => [`${c.kind}:${c.id}`, c]));
  const re = /\[(lawsuit|regulation):([0-9a-f-]{8,})\]/gi;
  const parts = [];
  let lastIdx = 0;
  let m;
  while ((m = re.exec(text)) !== null) {
    if (m.index > lastIdx) parts.push(text.slice(lastIdx, m.index));
    const key = `${m[1].toLowerCase()}:${m[2]}`;
    const c = byId.get(key);
    if (c) {
      parts.push(
        <Link
          key={`cite-${m.index}`}
          to={c.kind === 'lawsuit' ? `/legal/lawsuits/${c.id}` : `/legal/regulations/${c.id}`}
          style={{
            fontSize: 10, padding: '0 5px', borderRadius: 6,
            verticalAlign: 'super', lineHeight: 1.2,
            background: c.kind === 'lawsuit' ? '#EEF2FF' : '#D1FAE5',
            color: c.kind === 'lawsuit' ? '#4F46E5' : '#065F46',
            textDecoration: 'none', fontWeight: 700,
          }}
          title={c.name}
        >{c.kind === 'lawsuit' ? '⚖' : '📜'}</Link>
      );
    }
    // Skip the marker even if not in citations map (don't render raw bracket text)
    lastIdx = m.index + m[0].length;
  }
  if (lastIdx < text.length) parts.push(text.slice(lastIdx));
  return parts;
}
